// Controller layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Connects the workflow and domain to the page. No business logic here.
import { useMachine } from "@xstate/react";
import { metricsWorkflow } from "../workflow/metrics.workflow.js";
import * as domain from "../domain/metrics.domain.js";
import MetricsPage from "../page/MetricsPage.jsx";

export default function MetricsController() {
  const [state, send] = useMachine(metricsWorkflow);
  const { items, selectedId, error } = state.context;

  return (
    <MetricsPage
      status={String(state.value)}
      error={error}
      regionCount={domain.regionCount(items)}
      totalRevenue={domain.totalRevenue(items)}
      bestRevenue={domain.bestRevenue(items)}
      lowestCost={domain.lowestCost(items)}
      avgConversion={domain.avgConversion(items)}
      asOf={domain.asOf(items)}
    />
  );
}
