// Component layer — generated by line-matcher. Reusable presentation only.
export default function PortfolioFigma1Row({ row, selected, onOpen }) {
  return (
    <tr data-selected={selected ? "true" : undefined}>
      <td>
        <span>01</span>
      </td>
      <td>
        <span>{row.name}</span> <span className="badge">L3</span>
      </td>
      <td className="num">
        <span>$38.4M</span> <span>{row.share}</span>
      </td>
      <td>
        <span>2.0</span> <span>-0.7</span> <span>peer 2.7</span>
      </td>
      <td className="num">
        <span>{row.savings}</span> <span>{row.savingsPct}</span>
      </td>
      <td>
        <span className="badge err">3 high flags</span>{" "}
        <span className="badge err">widest maturity gap</span>
      </td>
      <td>
        <svg width="64" height="20" viewBox="0 0 64 20">
          <path d="m2 6 12 2 12-1 12 5 12 2 12 4" fill="none" stroke="currentColor" />
        </svg>
      </td>
      <td className="actions">
        <button onClick={() => onOpen(row.id)}>Open</button>
      </td>
    </tr>
  );
}
