// Domain layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Pure functions only: no network, storage or DOM.

export function asText(v) {
  return String(v);
}

export function moneyFull(v) {
  return "$" + Number(v).toLocaleString("en-US");
}

export function dateShort(v) {
  const d = new Date(v);
  const m = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return d.getUTCDate() + " " + m[d.getUTCMonth()] + " " + d.getUTCFullYear();
}

// Rows for the "orders" list.
export function toOrderRows(items) {
  return items.map((item) => ({
    id: item.id,
    number: asText(item.number),
    customer: asText(item.customer),
    total: moneyFull(item.total),
    placedOn: dateShort(item.placedOn),
  }));
}

// "orderCount" = count. Design showed "3".
export function orderCount(items) {
  return asText(items.length);
}

// "totalValue" = sum(total), shown as moneyFull. Design showed "$10,660".
export function totalValue(items) {
  return moneyFull(items.reduce((s, x) => s + Number(x.total), 0));
}

export function findOrder(items, id) {
  return items.find((item) => item.id === id) ?? null;
}

// Form text -> the types the API expects (taken from the example request body).
export function toOrderInput(values) {
  return {
    customer: String(values.customer ?? "").trim(),
    total: Number(values.total),
    notes: String(values.notes ?? "").trim(),
  };
}

// Raw values to prefill the form when an item is selected.
export function toFormValues(item) {
  if (!item) return {};
  return {
    customer: item.customer,
    total: item.total,
    notes: item.notes,
  };
}
