// Step 5 — write the code for each layer from the plan. Plain templates, no model.
import { FORMATTERS, AGGREGATES } from "./transforms.mjs";
import { listItems, envelopeOf } from "./match.mjs";

const cap = (s) => s[0].toUpperCase() + s.slice(1);
/**
 * The generated prop/handler name for an action, e.g. `"save"` -> `"onSave"`.
 *
 * @param {string} action An action name.
 * @returns {string} `"on" + PascalCase(action)`.
 */
export const handlerName = (action) => "on" + action.split(/[-_\s]+/).map(cap).join("");
/**
 * The generated workflow event name for an action, e.g. `"save"` -> `"SAVE"`.
 *
 * @param {string} action An action name.
 * @returns {string} `SCREAMING_SNAKE_CASE(action)`.
 */
export const eventName = (action) => action.toUpperCase().replace(/[-\s]+/g, "_");
const HEADER = (layer, extra = "") => `// ${layer} layer — generated by line-matcher. Do not add logic that belongs to another layer.${extra ? "\n// " + extra : ""}\n`;

/**
 * The generated Service layer's function names.
 *
 * @param {{Feature: string, Item: string}} n From `plan.mjs` `makeNames`.
 * @returns {{list: string, create: string, update: string, remove: string}}
 */
export function fnNames(n) {
  return {
    list: `list${n.Feature}`,
    create: `create${n.Item}`,
    update: `update${n.Item}`,
    remove: `delete${n.Item}`,
  };
}

// The comment above a placeholder's drafted body. An expression written in the Part inspector says who wrote it and, when it
// does not reproduce the design yet, says so (its test then stays a todo instead of failing).
const bodyNote = (p, what) => (p.unverified ? `// Written by you in the inspector. It does NOT reproduce the design's ${what} yet — check it.` : p.by === "you" ? `// Written by you and checked against the design's ${what} — review it.` : `// Drafted by AI and checked against the design's ${what} — review it.`);

// ---------------- Service ----------------
/**
 * Emit the Service layer: one function per wired API endpoint, plus a placeholder for any value that needs an
 * endpoint that does not exist yet. Plain template, no model.
 *
 * @param {object} plan From `plan.mjs` `makePlan`.
 * @returns {string} The generated JS source.
 */
export function emitService(plan) {
  const f = fnNames(plan.names);
  const toUrl = (p) => "`" + p.replace(/:([A-Za-z_]+)/, "${encodeURIComponent($1)}") + "`";
  const e = plan.endpoints;
  const lines = [HEADER("Service", "External I/O only: one function per API endpoint.")];
  lines.push(`async function request(method, url, body) {
  const res = await fetch(url, {
    method,
    headers: body ? { "Content-Type": "application/json" } : undefined,
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) throw new Error(\`\${method} \${url} failed with \${res.status}\`);
  return res.status === 204 ? null : res.json();
}
`);
  const param = (p) => (p.match(/:([A-Za-z_]+)/) ?? [])[1];
  if (e.list) lines.push(`export const ${f.list} = () => request("GET", ${toUrl(e.list.path)});`);
  else lines.push(`// PLACEHOLDER: ${plan.block?.kind === "missing" ? "there is no API contract yet" : "the API contract has no list endpoint"}, so nothing can be loaded. It fails on purpose rather than returning made-up data.
export const ${f.list} = () => Promise.reject(new Error("no list endpoint in the API contract yet"));`);
  if (e.create) lines.push(`export const ${f.create} = (data) => request("POST", ${toUrl(e.create.path)}, data);`);
  if (e.update) lines.push(`export const ${f.update} = (${param(e.update.path)}, data) => request("${e.update.method}", ${toUrl(e.update.path)}, data);`);
  if (e.remove) lines.push(`export const ${f.remove} = (${param(e.remove.path)}) => request("DELETE", ${toUrl(e.remove.path)});`);
  for (const v of plan.values.filter((v) => v.custom && v.from === "api")) {
    lines.push(`
// PLACEHOLDER: "${v.name}" needs an API endpoint that doesn't exist yet. The design showed ${JSON.stringify(v.example)}.
// Replace the body with a real request (use request(...) above) once the endpoint is defined.
export async function ${v.fn}() {
  return ${JSON.stringify(v.example)};
}`);
  }
  return lines.join("\n") + "\n";
}

// ---------------- Domain ----------------
/**
 * Emit the Domain layer: pure functions only (row-building, formatters actually used, computed values,
 * placeholders, form conversion). No network, storage or DOM.
 *
 * @param {object} plan From `plan.mjs` `makePlan`.
 * @returns {string} The generated JS source.
 */
export function emitDomain(plan) {
  const n = plan.names;
  const rowFields = plan.rowFields.filter((f) => f.field);
  const used = new Set([...rowFields.map((f) => f.formatter), ...plan.values.filter((v) => v.agg).map((v) => v.formatter)]);
  const out = [HEADER("Domain", "Pure functions only: no network, storage or DOM.")];
  if (plan.values.some((v) => v.agg === "field")) out.push('// Reads a dotted path ("a.b.c") from the response.\nconst get = (o, path) => path.split(".").reduce((x, k) => x?.[k], o);\n');

  for (const fmt of FORMATTERS.filter((x) => used.has(x.name))) out.push("export " + fmt.fn.toString() + "\n");

  const s = plan.sort;
  const sortCode =
    s.dir === "none"
      ? "items"
      : `[...items].sort((a, b) => {
    const x = a.${s.field}, y = b.${s.field};
    const c = typeof x === "number" && typeof y === "number" ? x - y : String(x).localeCompare(String(y));
    return ${s.dir === "asc" ? "c" : "-c"};
  })`;
  out.push(`// Rows for the "${n.feature}" list${s.dir !== "none" ? `, ${s.label}` : ""}.
export function to${n.Item}Rows(items) {
  return ${sortCode}.map((item) => ({
    id: item.${plan.idField},
${plan.rowFields.filter((f) => f.field || (f.custom && f.from === "fields")).map((f) => (f.field ? `    ${f.name}: ${f.formatter}(item.${f.field}),` : `    ${f.name}: ${f.fn}(item),`)).join("\n")}
  }));
}
`);

  for (const f of plan.rowFields.filter((f) => f.custom && f.from === "fields")) {
    out.push(`// PLACEHOLDER: "${f.name}" is built from ${f.inputs.join(", ")}. Design showed ${f.examples.map((x) => JSON.stringify(x)).join(", ")}.
${f.body ? bodyNote(f, "examples") : "// Starting point only — replace the body with the real logic."}
export function ${f.fn}(item) {
  return ${f.body ?? `[${f.inputs.map((i) => `item.${i}`).join(", ")}].join(" ")`};
}
`);
  }

  for (const v of plan.values) {
    if (v.agg === "field") {
      out.push(`// "${v.name}" = the response field "${v.field}"${v.formatter !== "asText" ? `, shown as ${v.formatter}` : ""}. Design showed "${v.example}".
export function ${v.name}(data) {
  return ${v.formatter}(get(data, ${JSON.stringify(v.field)}));
}
`);
    } else if (v.agg) {
      const agg = AGGREGATES.find((a) => a.name === v.agg);
      out.push(`// "${v.name}" = ${v.agg}${v.field ? `(${v.field})` : ""}${v.formatter !== "asText" ? `, shown as ${v.formatter}` : ""}. Design showed "${v.example}".
export function ${v.name}(items) {
  return ${v.formatter}(${agg.code("items", v.field)});
}
`);
    } else if (v.custom && v.from === "fields") {
      out.push(`// PLACEHOLDER: "${v.name}" is built from ${v.inputs.join(", ")} of the list. Design showed ${JSON.stringify(v.example)}.
${v.body ? bodyNote(v, "example") : "// Returns the design's example until the real logic is written."}
export function ${v.fn}(items, data) {
  return ${v.body ?? JSON.stringify(v.example)};
}
`);
    } else if (v.todo) {
      out.push(`// TODO: "${v.name}" (design showed "${v.example}") ${v.skipped ? "was skipped in Q&A — decide where it comes from." : "is not in the API yet."}
export function ${v.name}() {
  return "—";
}
`);
    }
  }

  out.push(`export function find${n.Item}(items, id) {
  return items.find((item) => item.${plan.idField} === id) ?? null;
}
`);

  if (plan.form) {
    const conv = (f) =>
      f.apiType === "number" ? `Number(values.${f.name})` : f.apiType === "boolean" ? `values.${f.name} === "on"` : `String(values.${f.name} ?? "").trim()`;
    out.push(`// Form text -> the types the API expects (taken from the example request body).
export function to${n.Item}Input(values) {
  return {
${plan.form.fields.map((f) => `    ${f.name}: ${conv(f)},`).join("\n")}
  };
}

// Raw values to prefill the form when an item is selected.
export function toFormValues(item) {
  if (!item) return {};
  return {
${plan.form.fields.map((f) => `    ${f.name}: item.${f.name},`).join("\n")}
  };
}
`);
  }
  return out.join("\n");
}

// Tests: the design's own values are the expected output for the mock data.
/**
 * Emit the Domain layer's test file: the design's own example values are asserted as the expected output against
 * the mock API data. A placeholder whose body is unverified (or has none yet) gets a `todo` test.
 *
 * @param {object} plan From `plan.mjs` `makePlan`.
 * @returns {string} The generated `node:test` source.
 */
export function emitDomainTest(plan) {
  const n = plan.names;
  const items = JSON.stringify(listItems(plan.endpoints), null, 2);
  const envelope = envelopeOf(plan.endpoints); // T16.3: the one place this is unwrapped (was a second, inline copy of this same logic)
  const rowFields = plan.rowFields.filter((f) => f.field);
  const expectedRows = (rowFields[0]?.examples ?? []).map((_, i) =>
    Object.fromEntries(rowFields.map((f) => [f.name, f.examples[i]]))
  );
  const valueTests = plan.values
    .filter((v) => v.agg)
    .map((v) => `test("${v.name} matches the design", () => {
  assert.equal(domain.${v.name}(${v.agg === "field" ? "data" : "items"}), ${JSON.stringify(v.example)});
});`)
    .join("\n\n");
  const todo = `{ todo: "placeholder — write the real logic" }`;
  const placeholderTests = [
    ...plan.rowFields
      .filter((f) => f.custom && f.from === "fields")
      .map((f) => `test("row.${f.name} matches the design", ${f.body && !f.unverified ? "{}" : todo}, () => {
  const rows = domain.to${n.Item}Rows(items);
  assert.deepEqual(rows.slice(0, ${f.examples.length}).map((r) => r.${f.name}), ${JSON.stringify(f.examples)});
});`),
    ...plan.values
      .filter((v) => v.custom && v.from === "fields")
      .map((v) => `test("${v.name} matches the design", ${v.body && !v.unverified ? "{}" : todo}, () => {
  assert.equal(domain.${v.fn}(items, ${envelope ? "data" : "undefined"}), ${JSON.stringify(v.example)});
});`),
  ].join("\n\n");
  return `// Generated from the design + mock API. Run: node --test
import { test } from "node:test";
import assert from "node:assert/strict";
import * as domain from "./${n.feature}.domain.js";

const items = ${items};
${envelope ? `const data = ${JSON.stringify(envelope, null, 2)};\n` : ""}
test("rows match the design (values and order)", ${plan.sort.skipped ? `{ todo: "row order is not resolved yet — see the open items" }, ` : ""}() => {
  // Only the parts matched to real API fields; placeholder parts have their own tests below.
  const keys = ${JSON.stringify(rowFields.map((f) => f.name))};
  const rows = domain.to${n.Item}Rows(items).map((row) => Object.fromEntries(keys.map((k) => [k, row[k]])));
  assert.deepEqual(rows.slice(0, ${expectedRows.length}), ${JSON.stringify(expectedRows, null, 2)});
});

${valueTests}

${placeholderTests}
`;
}

// ---------------- Workflow (XState) ----------------
/**
 * Emit the Workflow layer: an XState machine (loading/ready/creating/updating/removing/failed) wired to the
 * Service layer's functions, with one event per action.
 *
 * @param {object} plan From `plan.mjs` `makePlan`.
 * @returns {string} The generated JS source.
 */
export function emitWorkflow(plan) {
  const n = plan.names;
  const f = fnNames(n);
  const kinds = new Set(plan.actions.map((a) => a.kind));
  const need = {
    creating: kinds.has("save") || kinds.has("create"),
    updating: kinds.has("save") || kinds.has("update"),
    removing: kinds.has("remove"),
  };
  const actors = [`    load: fromPromise(() => service.${f.list}()),`];
  if (need.creating) actors.push(`    create: fromPromise(({ input }) => service.${f.create}(input.data)),`);
  if (need.updating) actors.push(`    update: fromPromise(({ input }) => service.${f.update}(input.id, input.data)),`);
  if (need.removing) actors.push(`    remove: fromPromise(({ input }) => service.${f.remove}(input.id)),`);

  const on = plan.actions.map((a) => {
    const ev = eventName(a.name);
    switch (a.kind) {
      case "save":
        return `        ${ev}: [{ guard: "hasSelection", target: "updating" }, { target: "creating" }],`;
      case "create": return `        ${ev}: { target: "creating" },`;
      case "update": return `        ${ev}: { guard: "hasSelection", target: "updating" },`;
      case "remove": return `        ${ev}: { target: "removing" },`;
      case "select": return `        ${ev}: { actions: assign({ selectedId: ({ event }) => event.id, error: null }) },`;
      case "clear": return `        ${ev}: { actions: assign({ selectedId: null }) },`;
      case "reload": return `        ${ev}: { target: "loading" },`;
      default: return "";
    }
  }).filter(Boolean);

  const mutation = (state, src, input) => `    ${state}: {
      invoke: {
        src: "${src}",
        input: ${input},
        onDone: { target: "loading", actions: assign({ selectedId: null }) },
        onError: { target: "ready", actions: "setError" },
      },
    },`;

  return `${HEADER("Workflow", "Application flow and state (XState). Talks to the Service layer only.")}import { setup, assign, fromPromise } from "xstate";
import * as service from "../service/${n.feature}.service.js";

export const ${n.fid}Workflow = setup({
  actors: {
${actors.join("\n")}
  },
  actions: {
    setError: assign({ error: ({ event }) => String(event.error?.message ?? event.error) }),
  },
  guards: {
    hasSelection: ({ context }) => context.selectedId != null,
  },
}).createMachine({
  id: "${n.feature}",
  initial: "loading",
  context: { ${plan.listKey ? "data: null, " : ""}items: [], selectedId: null, error: null },
  states: {
    loading: {
      invoke: {
        src: "load",
        onDone: { target: "ready", actions: assign({ ${plan.listKey ? `data: ({ event }) => event.output, items: ({ event }) => event.output[${JSON.stringify(plan.listKey)}] ?? []` : "items: ({ event }) => event.output"}, error: null }) },
        onError: { target: "failed", actions: "setError" },
      },
    },
    ready: {
      on: {
${on.join("\n")}
      },
    },
${need.creating ? mutation("creating", "create", "({ event }) => ({ data: event.data })") : ""}
${need.updating ? mutation("updating", "update", "({ context, event }) => ({ id: context.selectedId, data: event.data })") : ""}
${need.removing ? mutation("removing", "remove", "({ event }) => ({ id: event.id })") : ""}
    failed: {
      on: { RETRY: "loading" },
    },
  },
});
`.replace(/\n{3,}/g, "\n");
}

// ---------------- Controller ----------------
/**
 * Emit the Controller layer: wires the Workflow and Domain layers to the generated Page component, with
 * placeholders for controller-provided values/fields/actions. No business logic here.
 *
 * @param {object} plan From `plan.mjs` `makePlan`.
 * @returns {string} The generated JSX source.
 */
export function emitController(plan) {
  const n = plan.names;
  const props = [`      status={String(state.value)}`, `      error={error}`];
  const blocks = [];
  const hooks = [];
  let usesService = false;
  for (const v of plan.values) {
    if (v.custom) {
      if (v.from === "fields") props.push(`      ${v.name}={domain.${v.fn}(items${plan.listKey ? ", data" : ""})}`);
      else if (v.from === "controller") {
        blocks.push(`// PLACEHOLDER: "${v.name}" is provided by the controller. The design showed ${JSON.stringify(v.example)}.
function ${v.fn}() {
  return ${JSON.stringify(v.example)};
}`);
        props.push(`      ${v.name}={${v.fn}()}`);
      } else {
        usesService = true;
        hooks.push(`  const [${v.name}, set${cap(v.name)}] = useState(undefined);
  useEffect(() => {
    service.${v.fn}().then(set${cap(v.name)});
  }, []);`);
        props.push(`      ${v.name}={${v.name}}`);
      }
    } else if (v.agg || v.todo) props.push(`      ${v.name}={domain.${v.name}(${v.agg === "field" ? "data" : "items"})}`);
  }
  if (plan.rowFields.length) {
    const fromController = plan.rowFields.filter((f) => f.custom && f.from === "controller");
    for (const f of fromController) {
      blocks.push(`// PLACEHOLDER: "row.${f.name}" is provided by the controller for each row. The design showed ${f.examples.map((x) => JSON.stringify(x)).join(", ")}.
function ${f.fn}(row) {
  return ${JSON.stringify(f.examples[0] ?? "—")};
}`);
    }
    const rows = `domain.to${n.Item}Rows(items)`;
    props.push(
      fromController.length ? `      rows={${rows}.map((row) => ({ ...row, ${fromController.map((f) => `${f.name}: ${f.fn}(row)`).join(", ")} }))}` : `      rows={${rows}}`,
      `      selectedId={selectedId}`,
    );
  }
  if (plan.form) props.push(`      formValues={domain.toFormValues(domain.find${n.Item}(items, selectedId))}`);
  for (const a of plan.actions) {
    const h = handlerName(a.name), ev = eventName(a.name);
    const isFormAction = plan.form && a.name === plan.form.action;
    if (a.kind === "custom") {
      blocks.push(`// PLACEHOLDER: "${a.name}" ${a.scope} action — decide what it should do.
function ${a.fn}(${a.scope === "row" ? "id" : isFormAction ? "values" : ""}) {
  console.warn("${a.fn} is a placeholder"${a.scope === "row" ? ", id" : isFormAction ? ", values" : ""});
}`);
      props.push(`      ${h}={${a.fn}}`);
    } else if (isFormAction) props.push(`      ${h}={(values) => send({ type: "${ev}", data: domain.to${n.Item}Input(values) })}`);
    else if (a.scope === "row") props.push(`      ${h}={(id) => send({ type: "${ev}", id })}`);
    else props.push(`      ${h}={() => send({ type: "${ev}" })}`);
  }
  const react = hooks.length ? `import { useState, useEffect } from "react";\n` : "";
  return `${HEADER("Controller", "Connects the workflow and domain to the page. No business logic here.")}${react}import { useMachine } from "@xstate/react";
import { ${n.fid}Workflow } from "../workflow/${n.feature}.workflow.js";
import * as domain from "../domain/${n.feature}.domain.js";
${usesService ? `import * as service from "../service/${n.feature}.service.js";\n` : ""}import ${n.Feature}Page from "../page/${n.Feature}Page.jsx";
${blocks.length ? "\n" + blocks.join("\n\n") + "\n" : ""}
export default function ${n.Feature}Controller() {
  const [state, send] = useMachine(${n.fid}Workflow);
  const { ${plan.listKey ? "data, " : ""}items, selectedId, error } = state.context;
${hooks.length ? hooks.join("\n") + "\n" : ""}
  return (
    <${n.Feature}Page
${props.join("\n")}
    />
  );
}
`;
}

// ---------------- Route ----------------
/**
 * Emit the Route layer: the navigation entry point, delegating to the generated Controller.
 *
 * @param {object} plan From `plan.mjs` `makePlan`.
 * @returns {string} The generated JSX source.
 */
export function emitRoute(plan) {
  const n = plan.names;
  return `${HEADER("Route", "Navigation entry point. Delegates to the controller.")}import ${n.Feature}Controller from "../controller/${n.Feature}Controller.jsx";

export const path = ${JSON.stringify(plan.route)};

export default function ${n.Feature}Route() {
  return <${n.Feature}Controller />;
}
`;
}

// ---------------- Mock API ----------------
/**
 * Emit the mock API: an in-memory `fetch` patch (`installMockApi`, itself part of the generated source, not this
 * module) seeded from the example responses, with routes for the wired list/create/update/remove endpoints.
 *
 * @param {object} plan From `plan.mjs` `makePlan`.
 * @returns {string} The generated JS source.
 */
export function emitMock(plan) {
  const e = plan.endpoints;
  const re = (p) => "/^" + p.replace(/\//g, "\\/").replace(/:[A-Za-z_]+/, "([^/]+)") + "$/";
  const id = plan.idField;
  const routes = [];
  if (e.list) routes.push(`  { method: "GET", pattern: ${re(e.list.path)}, handle: () => [200, ${plan.listKey ? `{ ...seed, ${JSON.stringify(plan.listKey)}: db }` : "db"}] },`);
  if (e.create) routes.push(`  { method: "POST", pattern: ${re(e.create.path)}, handle: (body) => {
      const item = { ...body, ${id}: nextId++ };
      db.push(item);
      return [201, item];
    } },`);
  if (e.update) routes.push(`  { method: "${e.update.method}", pattern: ${re(e.update.path)}, handle: (body, key) => {
      const i = db.findIndex((x) => String(x.${id}) === key);
      if (i < 0) return [404, { error: "not found" }];
      db[i] = { ...db[i], ...body, ${id}: db[i].${id} };
      return [200, db[i]];
    } },`);
  if (e.remove) routes.push(`  { method: "DELETE", pattern: ${re(e.remove.path)}, handle: (_body, key) => {
      const before = db.length;
      db = db.filter((x) => String(x.${id}) !== key);
      return db.length < before ? [204, null] : [404, { error: "not found" }];
    } },`);

  const note = plan.block ? `// ${plan.block.kind === "missing" ? "No API contract yet: this mock has no routes and no data." : plan.block.why + " The mock list starts empty."}\n` : "";
  return `// Mock API — generated from the example responses you gave. In-memory, resets on reload.
${note}const seed = ${JSON.stringify(e.list?.response ?? [], null, 2)};

let db = structuredClone(${plan.listKey ? `seed[${JSON.stringify(plan.listKey)}]` : "seed"});
let nextId = Math.max(0, ...db.map((x) => Number(x.${id}) || 0)) + 1;

const routes = [
${routes.join("\n")}
];

export function installMockApi({ delay = 200 } = {}) {
  const realFetch = window.fetch.bind(window);
  window.fetch = async (input, init = {}) => {
    const url = new URL(typeof input === "string" ? input : input.url, window.location.origin);
    const method = (init.method ?? "GET").toUpperCase();
    for (const r of routes) {
      const m = r.method === method && url.pathname.match(r.pattern);
      if (!m) continue;
      await new Promise((res) => setTimeout(res, delay));
      const body = init.body ? JSON.parse(init.body) : undefined;
      const [status, data] = r.handle(body, m[1] && decodeURIComponent(m[1]));
      console.info("[mock]", method, url.pathname, status);
      return new Response(status === 204 ? null : JSON.stringify(data), {
        status,
        headers: { "Content-Type": "application/json" },
      });
    }
    return realFetch(input, init);
  };
}
`;
}
