// Page layer — generated by line-matcher from the design. Props in, JSX out; no business logic.
import InvoiceRow from "../component/InvoiceRow.jsx";

export default function InvoicesPage({
  status,
  error,
  invoiceCount,
  totalBilled,
  largestInvoice,
  syncedAt,
  rows,
  selectedId,
  formValues,
  onEdit,
  onArchive,
  onDelete,
  onSave,
  onCancel,
}) {
  return (
    <main className="page">
      {status === "loading" && <p className="status">Loading…</p>}
      {error && (
        <p role="alert" className="error">
          {error}
        </p>
      )}
      <header className="header">
        <h1>Invoices</h1>
        <p className="meta">
          <span>{invoiceCount}</span> invoices · <span>{totalBilled}</span> billed · largest{" "}
          <span>{largestInvoice}</span> · synced <span>{syncedAt}</span>
        </p>
      </header>

      <form
        className="card form"
        key={selectedId ?? "new"}
        onSubmit={(e) => {
          e.preventDefault();
          onSave(Object.fromEntries(new FormData(e.currentTarget)));
        }}
      >
        <input name="vendor" placeholder="Vendor" required defaultValue={formValues.vendor ?? ""} />
        <input
          name="amount"
          type="number"
          placeholder="Amount (USD)"
          required
          defaultValue={formValues.amount ?? ""}
        />
        <input
          name="requester"
          placeholder="Requested by"
          required
          defaultValue={formValues.requester ?? ""}
        />
        <button type="submit" className="primary">
          Save
        </button>
        <button type="button" onClick={onCancel}>
          Cancel
        </button>
      </form>

      <table className="card table">
        <thead>
          <tr>
            <th>Invoice</th>
            <th>Vendor</th>
            <th>Amount</th>
            <th>Due</th>
            <th>Requested by</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <InvoiceRow
              key={row.id}
              row={row}
              selected={row.id === selectedId}
              onEdit={onEdit}
              onArchive={onArchive}
              onDelete={onDelete}
            />
          ))}
        </tbody>
      </table>
    </main>
  );
}
