// Component layer — generated by line-matcher. Reusable presentation only.
export default function CategoryRow({ row, selected, onEdit, onDelete }) {
  return (
    <tr data-selected={selected ? "true" : undefined}>
      <td>{row.name}</td>
      <td className="num">{row.spend}</td>
      <td>{row.owner}</td>
      <td className="actions">
        <button onClick={() => onEdit(row.id)}>Edit</button>
        <button className="danger" onClick={() => onDelete(row.id)}>
          Delete
        </button>
      </td>
    </tr>
  );
}
