import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { loadConfig } from '../packages/core/config.mjs';
import {
  dependencyCruiserBoundaryRules, renderDependencyCruiserConfig, notExpressibleRules, renderCiExport, EXPORT_CI_TARGETS,
} from '../packages/core/exportCi.mjs';
import { makeTempDir } from '../test-utils/tmpdir.mjs';

const defaultConfig = () => loadConfig(makeTempDir('export-ci-'));

test('dependencyCruiserBoundaryRules: default layers include the six named boundary rules from #437\'s report (docs/EXPLORATION-2026-09-oss-plugins.md section 8)', () => {
  const names = dependencyCruiserBoundaryRules(defaultConfig()).map((r) => r.name);
  for (const expected of ['page-to-workflow', 'page-to-service', 'page-to-domain', 'component-to-app-logic', 'workflow-to-ui', 'service-to-ui']) {
    assert.ok(names.includes(expected), `expected ${expected} in ${names.join(', ')}`);
  }
});

test('dependencyCruiserBoundaryRules: also covers every other default layer (route/controller/hook/domain/expression) the old static file never did', () => {
  const names = dependencyCruiserBoundaryRules(defaultConfig()).map((r) => r.name);
  for (const expected of ['route-boundary', 'controller-boundary', 'hook-boundary', 'domain-boundary', 'expression-boundary']) {
    assert.ok(names.includes(expected), `expected ${expected} in ${names.join(', ')}`);
  }
});

test('dependencyCruiserBoundaryRules: turning a boundary rule code off in architecture.yml drops the matching generated rule', () => {
  const dir = makeTempDir('export-ci-');
  fs.writeFileSync(path.join(dir, 'architecture.yml'), 'rules:\n  WORKFLOW-001: off\n');
  const names = dependencyCruiserBoundaryRules(loadConfig(dir)).map((r) => r.name);
  assert.ok(!names.includes('workflow-to-ui'));
  assert.ok(names.includes('workflow-boundary'), 'workflow still gets the generic complement rule for its other disallowed edges');
});

test('dependencyCruiserBoundaryRules: a project with a custom layer gets a rule for its own edges', () => {
  const dir = makeTempDir('export-ci-');
  fs.writeFileSync(path.join(dir, 'architecture.yml'), [
    'layers:',
    '  repository:',
    "    pattern: 'features/*/repository/**'",
    '    canImport: [domain, types]',
  ].join('\n'));
  const rules = dependencyCruiserBoundaryRules(loadConfig(dir));
  const own = rules.find((r) => r.name === 'repository-boundary');
  assert.ok(own, 'expected a repository-boundary rule');
  assert.ok(!own.toPatterns.some((p) => p.includes('domain')), 'repository may import domain, so domain must not be in its own forbidden targets');
});

test('renderDependencyCruiserConfig: header, hash and a not-expressible list are present', () => {
  const out = renderDependencyCruiserConfig(defaultConfig());
  assert.match(out, /generated by Construct/);
  assert.match(out, /\/\/ hash: [0-9a-f]{16}/);
  assert.match(out, /Not expressible as a path rule.*DOMAIN-001.*PAGE-001/s);
  assert.match(out, /module\.exports = /);
});

test('renderDependencyCruiserConfig: is valid, requireable CommonJS with the expected forbidden rule count', () => {
  const dir = makeTempDir('export-ci-');
  const out = renderDependencyCruiserConfig(loadConfig(dir));
  const file = path.join(dir, '.dependency-cruiser.cjs');
  fs.writeFileSync(file, out);
  const mod = createRequire(import.meta.url)(file);
  assert.ok(Array.isArray(mod.forbidden) && mod.forbidden.length > 0);
});

test('renderDependencyCruiserConfig: frozen and nonLayer globs land in options.exclude', () => {
  const dir = makeTempDir('export-ci-');
  fs.writeFileSync(path.join(dir, 'architecture.yml'), "frozen: ['vendor/**']\nnonLayer: ['features/*/tests/**']\n");
  const out = renderDependencyCruiserConfig(loadConfig(dir));
  assert.match(out, /vendor/);
  assert.match(out, /tests/);
});

test('notExpressibleRules: excludes the six boundary codes, includes semantic/AST-only codes', () => {
  const codes = notExpressibleRules(defaultConfig());
  for (const boundary of ['PAGE-002', 'PAGE-003', 'PAGE-005', 'COMPONENT-002', 'COMPONENT-003', 'WORKFLOW-001', 'SERVICE-002']) {
    assert.ok(!codes.includes(boundary), `${boundary} should be expressible, not listed`);
  }
  for (const semantic of ['PAGE-001', 'DOMAIN-001', 'SERVICE-001', 'HOOK-001', 'READ-001', 'SLICE-001']) {
    assert.ok(codes.includes(semantic), `${semantic} should be in the not-expressible list`);
  }
});

test('renderCiExport: unknown target throws', () => {
  assert.throws(() => renderCiExport(makeTempDir('export-ci-'), defaultConfig(), 'bogus'), /Unknown export ci target/);
});

test('renderCiExport: eslint-boundaries target reuses exportArchitectureRules.mjs\'s generator (#513)', () => {
  const dir = makeTempDir('export-ci-');
  const out = renderCiExport(dir, loadConfig(dir), 'eslint-boundaries');
  assert.match(out, /eslint-plugin-boundaries/);
  assert.match(out, /boundaries\/dependencies/);
});

test('EXPORT_CI_TARGETS lists both targets', () => {
  assert.deepEqual([...EXPORT_CI_TARGETS].sort(), ['dependency-cruiser', 'eslint-boundaries']);
});
