// #659 (part of epic #616) -- the generated Playwright browser flows of the detail, form, dashboard and wizard shapes (the list's is in test/proof.test.mjs).
// Always run: what the generator writes per shape (the file, the locked header, deterministic bytes, regenerated by the command in its own header, valid
// TypeScript, the state names the runner classifies), that a project with no Playwright config or a local data source gets none, and the plan steps a
// project with Playwright configured ends its chain with. Opt-in (CONSTRUCT_RUN_PLAYWRIGHT=1, needs ui/e2e node_modules and chromium, like
// test/proof.test.mjs): each flow PASSES against the real generated screen in a real browser, and a deliberately broken screen FAILS it as an APP failure
// that names the state (the runner's classifyFailure), not as "the test could not finish".
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import ts from 'typescript';
import { PLAYWRIGHT_SHAPES, detectPlaywright, generateProof, proofFiles, proofTouches } from '../packages/core/proof.mjs';
import { GENERATED_MARKER } from '../packages/engine/testGenerator.mjs';
import { resolveSpecs, runFeatureTests } from '../packages/engine/testRunner.mjs';
import { HAVE_XSTATE, REPO, initProject, planFor, run } from '../test-utils/shapeChain.mjs';
import { makeTempDir } from '../test-utils/tmpdir.mjs';

/** One case per shape: the sentence (for the plan), the unit, the feature, the fields and how the layers are created. */
const CASES = {
  detail: { sentence: 'A user wants to see the details of a product', feature: 'product', name: 'Product', entity: 'Product', fields: 'id:string,name:string,price:number,inStock:boolean', route: '/product', layers: 'domain,service,hook,component,page,controller' },
  form: { sentence: 'A user wants to add a product with a name and a price', feature: 'add-product', name: 'AddProduct', entity: 'Product', fields: 'id:string,name:string,price:number,inStock:boolean', route: '/add-product', layers: 'domain,service,hook,component,page,controller' },
  dashboard: { sentence: 'A manager wants an overview of orders with totals', feature: 'orders-dashboard', name: 'OrdersDashboard', entity: 'Order', fields: 'id:string,total:number,paid:boolean', route: '/orders-dashboard', layers: 'domain,service,hook,component,page,controller' },
  wizard: { sentence: 'A user wants a step by step signup', feature: 'signup', name: 'Signup', entity: 'Signup', fields: 'id:string,name:string,age:number,newsletter:boolean', route: '/signup', layers: 'domain,service,workflow,hook,component,page,controller', steps: 'details,options,review,done' },
};
const SHAPES = Object.keys(CASES);

/** A `construct init` project with the feature of the case and its shape written (nothing linked, nothing planned). */
function project(shape, { playwright = true } = {}) {
  const c = CASES[shape];
  const dir = makeTempDir(`construct-browser-${shape}-`);
  assert.equal(run(['init', '--framework', 'react-spa'], dir).status, 0);
  assert.equal(run(['create', 'feature', c.feature], dir).status, 0);
  const layers = run(['create', 'layer', c.name, '--feature', c.feature, '--layers', c.layers, '--shape', shape, '--entity', c.entity, '--fields', c.fields, '--source', 'endpoint', ...(c.steps ? ['--steps', c.steps] : [])], dir);
  assert.equal(layers.status, 0, layers.stderr);
  if (playwright) fs.writeFileSync(path.join(dir, 'playwright.config.ts'), "export default { testDir: 'features' };\n");
  return dir;
}

const requestOf = (shape, extra = {}) => {
  const c = CASES[shape];
  return { name: c.name, feature: c.feature, shape, entity: c.entity, fields: c.fields, ...(c.steps ? { steps: c.steps } : {}), source: 'endpoint', kind: 'playwright', route: c.route, ...extra };
};
const specFile = (dir, shape) => path.join(dir, 'features', CASES[shape].feature, 'tests', 'generated', `${CASES[shape].name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()}--screen.spec.ts`);
const syntaxErrors = (text) => ts.transpileModule(text, { reportDiagnostics: true, compilerOptions: { target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ESNext } }).diagnostics.map((d) => ts.flattenDiagnosticMessageText(d.messageText, '\n'));

test('every shape has a browser flow now, and the flow is a pure function of the request', () => {
  assert.deepEqual([...PLAYWRIGHT_SHAPES], ['list', 'detail', 'form', 'dashboard', 'wizard']);
  for (const shape of SHAPES) {
    const dir = project(shape);
    const [file, ...more] = proofFiles(dir, requestOf(shape));
    assert.equal(more.length, 0, shape);
    assert.equal(file.path, specFile(dir, shape), shape);
    assert.equal(file.kind, 'playwright');
    assert.equal(file.content, proofFiles(dir, requestOf(shape))[0].content, `${shape}: the same request writes the same bytes`);
    assert.ok(file.content.startsWith(`${GENERATED_MARKER}\n`), `${shape}: locked generated-test header`);
    assert.match(file.content, new RegExp(`^// proof: "${CASES[shape].name}" \\(shape ${shape}, kind playwright\\)$`, 'm'));
    assert.match(file.content, /^\/\/ run: construct test run [a-z-]+ --area generated --name [a-z-]+--screen\.spec\.ts {3}\(the app must be running\)$/m);
    assert.ok(file.content.includes(`const START_URL: string | null = "${CASES[shape].route}";`), `${shape}: the route the plan wired is the address it loads (the runner reads this line)`);
    assert.deepEqual(syntaxErrors(file.content), [], `${shape}: valid TypeScript`);
    assert.deepEqual(proofTouches(dir, requestOf(shape)).map((f) => `${f.change} ${f.path.split('/').pop()}`), [`create ${path.basename(file.path)}`, 'modify architecture.yml']);
  }
});

test('what each flow checks: the states of the shape, named in the words the runner classifies', () => {
  const text = (shape) => proofFiles(project(shape), requestOf(shape))[0].content;
  const detail = text('detail');
  for (const want of ["toBe('loading')", "toBe('ready')", "toBe('not-found')", "toBe('error')", '<h1>Product details</h1>', '<dt>Price</dt>', '<dd>Yes</dd>', "page.route('**' + ENDPOINT + '/*'", "'id=' + encodeURIComponent(String(ITEM.id))", "getByRole('alert')"]) assert.ok(detail.includes(want), `detail: ${want}`);
  const form = text('form');
  for (const want of ["getByLabel(field.label, { exact: true })", 'label: "Price", type: "number"', 'label: "In stock", type: "checkbox"', "toBe('invalid')", '>Name is required.</span>', '>Price is required.</span>', "toBe('submitted')", 'Add another', 'const TYPED = { name: "name 1", price: 12.5, inStock: true };', "toBe('error')", "route.request().postData()"]) assert.ok(form.includes(want), `form: ${want}`);
  const dashboard = text('dashboard');
  for (const want of ["toBe('loading')", "toBe('ready')", '<h1>Orders Dashboard</h1>', '<li><span>Orders</span><strong>2</strong></li>', '<li><span>Sum of total</span><strong>19.5</strong></li>', '<section aria-label=\\"Total\\"><h2>Total</h2>', '<div><dt>Average</dt><dd>9.75</dd></div>', "toBe('error')"]) assert.ok(dashboard.includes(want), `dashboard: ${want}`);
  const wizard = text('wizard');
  for (const want of ['Step 1 of 4: Details', 'Step 4 of 4: Done', '<legend>Options</legend>', "press(page, 'Next')", "press(page, 'Back')", "press(page, 'Submit')", "toBe('submitted')", 'Signup complete.', 'Start again', "expectState('Next on the step \"' + STEPS[at].name + '\" with nothing typed', 'disabled'", 'const at = 0;', "toBe('error')"]) assert.ok(wizard.includes(want), `wizard: ${want}`);
  for (const t of [detail, form, dashboard, wizard]) assert.ok(t.includes('expect.poll('), 'a failed poll is what the runner reads: Expected and Received lines');
  assert.ok(form.includes("'.\\nExpected: \"' + quote(want)"), 'a one-shot comparison throws the same two lines');
});

test('the wizard flow follows the steps: two, three and four steps give the progress and the review of each', () => {
  const dir = project('wizard');
  for (const [steps, count] of [['details,done', 2], ['details,review,done', 3], ['details,options,review,done', 4]]) {
    const text = proofFiles(dir, requestOf('wizard', { steps }))[0].content;
    assert.equal(text.match(/progress: "<p/g).length, count, steps);
    assert.ok(text.includes(`Step ${count} of ${count}: Done`), steps);
    assert.deepEqual(syntaxErrors(text), [], steps);
    assert.ok(text.includes(`--steps ${steps} --route /signup`), 'regenerated by the same command, steps and route included');
  }
});

test('the header command regenerates the same bytes (it is a proof: edits are refused, regeneration is not)', () => {
  for (const shape of SHAPES) {
    const dir = project(shape);
    const created = run(['create', 'proof', CASES[shape].name, '--feature', CASES[shape].feature, '--shape', shape, '--kind', 'playwright', '--entity', CASES[shape].entity, '--fields', CASES[shape].fields, '--route', CASES[shape].route, ...(CASES[shape].steps ? ['--steps', CASES[shape].steps] : []), '--source', 'endpoint'], dir);
    assert.equal(created.status, 0, created.stderr);
    const file = specFile(dir, shape);
    const first = fs.readFileSync(file, 'utf8');
    const command = /^\/\/ Generated by `construct (.*)`\./m.exec(first)[1].split(' ');
    fs.rmSync(file);
    assert.equal(run(command, dir).status, 0);
    assert.equal(fs.readFileSync(file, 'utf8'), first, `${shape}: the command in the header writes the same file`);
    assert.equal(resolveSpecs(dir, CASES[shape].feature, { name: path.basename(file), area: 'generated' }).ok, true, `${shape}: construct test run picks it up as a generated spec`);
    assert.match(fs.readFileSync(path.join(dir, 'architecture.yml'), 'utf8'), /features\/\*\/tests\/generated\/\*\*/, `${shape}: locked (frozen) like the list flow`);
    fs.writeFileSync(file, '// my own file\n');
    assert.notEqual(run(command, dir).status, 0, `${shape}: a file that is not a generated proof is never overwritten`);
  }
});

test('no Playwright config, or a local data source, writes no browser flow and says why (nothing is installed)', () => {
  for (const shape of SHAPES) {
    const bare = project(shape, { playwright: false });
    assert.equal(detectPlaywright(bare), null);
    assert.deepEqual(proofFiles(bare, requestOf(shape)), []);
    assert.deepEqual(proofTouches(bare, requestOf(shape)), []);
    const none = generateProof(bare, requestOf(shape));
    assert.deepEqual([none.files, none.needs], [[], []]);
    assert.match(none.skipped, /Playwright is not configured in this project/);
    const configured = project(shape);
    assert.deepEqual(proofFiles(configured, requestOf(shape, { source: 'local' })), [], 'a local source makes no request to mock');
    assert.match(generateProof(configured, requestOf(shape, { source: 'local' })).skipped, /local data source makes no request/);
    const written = generateProof(configured, requestOf(shape));
    assert.deepEqual([written.files.length, written.skipped, written.needs], [1, null, ['@playwright/test']]);
  }
});

test('with a Playwright config the plan of each shape ends with its browser flow and the run of it, on the route the plan wired', async () => {
  for (const shape of SHAPES) {
    const c = CASES[shape];
    const dir = makeTempDir(`construct-browser-plan-${shape}-`);
    assert.equal(run(['init', '--framework', 'react-spa'], dir).status, 0);
    fs.writeFileSync(path.join(dir, 'playwright.config.ts'), "export default { testDir: 'features' };\n");
    const { planned } = await planFor(dir, c.sentence, c.feature, shape, 'endpoint');
    const flows = planned.plan.steps.filter((s) => (s.flow === 'create.proof' && s.args.kind === 'playwright') || s.flow === 'test.run');
    assert.deepEqual(flows.map((s) => s.flow), ['create.proof', 'test.run'], shape);
    assert.equal(flows[0].args.route, c.route, `${shape}: the flow opens the route the plan wired`);
    assert.equal(flows[0].args.shape, shape);
    assert.match(flows[1].args.name, /^[a-z-]+--screen\.spec\.ts$/);
    assert.equal(flows[1].args.area, 'generated');
    assert.equal(planned.proof.playwright.skipped, null, `${shape}: nothing is left out`);
    assert.equal(planned.proof.steps.filter((p) => p.kind === 'playwright').length, 1);
    assert.equal(planned.notes.some((n) => /no browser flow/i.test(n)), false, `${shape}: no "no browser flow" note`);
    const local = (await planFor(dir, c.sentence, c.feature, shape, 'local')).planned;
    assert.equal(local.plan.steps.some((s) => s.flow === 'test.run'), false, `${shape}: a local source has no browser flow`);
    assert.match(local.notes.join('\n'), /No browser flow is planned for .*local data source makes no request to mock/s);
  }
});

// ------------------------------------------------------------------------------------------------------- the browser (opt-in)

const browser = process.env.CONSTRUCT_RUN_PLAYWRIGHT === '1';
const NEEDS_BROWSER = { skip: (!browser && 'set CONSTRUCT_RUN_PLAYWRIGHT=1 (needs ui/e2e node_modules + chromium)') || (!HAVE_XSTATE && 'xstate, react-dom, esbuild and typescript are not installed here'), timeout: 240000 };

/** A project that has its shape written for real, Playwright configured and installed (the one Construct's own e2e suite ships), and the flow generated. */
function browserProject(shape) {
  const c = CASES[shape];
  const dir = initProject('react-spa', `browser-${shape}`);
  assert.equal(run(['create', 'feature', c.feature], dir).status, 0);
  const layers = run(['create', 'layer', c.name, '--feature', c.feature, '--layers', c.layers, '--shape', shape, '--entity', c.entity, '--fields', c.fields, '--source', 'endpoint', ...(c.steps ? ['--steps', c.steps] : [])], dir);
  assert.equal(layers.status, 0, layers.stderr);
  fs.writeFileSync(path.join(dir, 'playwright.config.ts'), "export default { testDir: 'features' };\n");
  for (const name of ['@playwright', 'playwright', 'playwright-core']) fs.symlinkSync(fs.realpathSync(path.join(REPO, 'ui', 'e2e', 'node_modules', name)), path.join(dir, 'node_modules', name));
  const created = run(['create', 'proof', c.name, '--feature', c.feature, '--shape', shape, '--kind', 'playwright', '--entity', c.entity, '--fields', c.fields, '--route', c.route, ...(c.steps ? ['--steps', c.steps] : []), '--source', 'endpoint'], dir);
  assert.equal(created.status, 0, created.stderr);
  return dir;
}

/** Bundles the controller of the screen into a page and serves it (any address answers the page: the app's route entry is not the subject here). */
async function serve(dir, shape) {
  const c = CASES[shape];
  const { build } = await import('esbuild');
  const out = path.join(dir, 'served');
  fs.rmSync(out, { recursive: true, force: true });
  fs.mkdirSync(out, { recursive: true });
  fs.writeFileSync(path.join(dir, 'entry.tsx'), `import { createRoot } from 'react-dom/client';\nimport { ${c.name}Controller } from './features/${c.feature}/controllers/${c.name}Controller.controller';\ncreateRoot(document.getElementById('root')!).render(<${c.name}Controller />);\n`);
  await build({ entryPoints: [path.join(dir, 'entry.tsx')], outfile: path.join(out, 'app.js'), bundle: true, platform: 'browser', format: 'iife', jsx: 'automatic', absWorkingDir: dir, logLevel: 'silent', alias: { react: fs.realpathSync(path.join(dir, 'node_modules', 'react')) } });
  const html = '<!doctype html><html><body><div id="root"></div><script src="/app.js"></script></body></html>';
  const server = http.createServer((req, res) => {
    if (req.url === '/app.js') { res.setHeader('content-type', 'text/javascript'); res.end(fs.readFileSync(path.join(out, 'app.js'))); } else { res.setHeader('content-type', 'text/html'); res.end(html); }
  });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  return server;
}

/** Runs the flow of the shape against the screen as it is now. */
async function runFlow(dir, shape) {
  const server = await serve(dir, shape);
  try {
    const name = path.basename(specFile(dir, shape));
    return await runFeatureTests(dir, CASES[shape].feature, { name, area: 'generated', baseUrl: `http://127.0.0.1:${server.address().port}` });
  } finally {
    await new Promise((resolve) => server.close(resolve));
  }
}

/** Replaces `from` by `to` in the one file of the feature that has it (a deliberate break of the screen). */
function breakScreen(dir, shape, from, to) {
  const root = path.join(dir, 'features', CASES[shape].feature);
  const hits = fs.readdirSync(root, { recursive: true }).map((f) => path.join(root, f)).filter((f) => fs.statSync(f).isFile() && !f.includes(`${path.sep}tests${path.sep}`) && fs.readFileSync(f, 'utf8').includes(from));
  assert.equal(hits.length, 1, `exactly one file has ${from}: ${hits.join(', ')}`);
  fs.writeFileSync(hits[0], fs.readFileSync(hits[0], 'utf8').replace(from, to));
}

/** What breaking each shape on purpose must name: the test that fails, and the state it expected and the one the screen reached. */
const BREAKS = {
  detail: { from: 'Product not found.', to: 'Product is gone.', title: 'Product screen: the not-found state', expected: 'not-found', reached: 'nothing' },
  form: { from: 'Product added.', to: 'Product saved.', title: 'AddProduct screen: a valid submit posts the typed values and shows the saved notice', expected: 'submitted', reached: 'nothing' },
  dashboard: { from: 'role="alert"', to: 'role="status"', title: 'OrdersDashboard screen: the error state, with role alert', expected: 'error', reached: 'nothing' },
  wizard: { from: 'hidden={isLast} disabled={!valid} onClick={onNext}', to: 'hidden={isLast} disabled={!valid} onClick={onBack}', title: 'Signup wizard: Next through every step, Back keeps what was typed, then Submit posts the typed values', expected: 'options', reached: 'details' },
};

for (const shape of SHAPES) {
  test(`the generated Playwright flow of the ${shape} shape PASSES against the real screen in a browser, and FAILS as an app failure naming the state when the screen is broken`, NEEDS_BROWSER, async () => {
    const dir = browserProject(shape);
    const good = await runFlow(dir, shape);
    assert.equal(good.ok, true, JSON.stringify(good));
    assert.ok(good.tests.length >= 2, `${shape}: ${good.tests.length} tests`);
    assert.deepEqual(good.tests.map((t) => t.status), good.tests.map(() => 'passed'), JSON.stringify(good.tests.map((t) => [t.title, t.status, t.failure?.message])));
    const b = BREAKS[shape];
    breakScreen(dir, shape, b.from, b.to);
    const bad = await runFlow(dir, shape);
    const failed = bad.tests.filter((t) => t.status === 'failed');
    assert.ok(failed.some((t) => t.title === b.title), JSON.stringify(failed.map((t) => [t.title, t.failure?.kind, t.failure?.message])));
    const one = failed.find((t) => t.title === b.title);
    assert.deepEqual([one.failure.kind, one.failure.expected, one.failure.reached], ['app', b.expected, b.reached], JSON.stringify(one.failure));
  });
}
