// @construct-generated tests v1 - LOCKED, do not edit (#348)
// Generated by `construct generate tests`. Regenerated whenever the workflow changes; edits are refused.
// To change it: clone it to features/shop/tests/ (one level up), where nothing regenerates it.
// feature: "shop"
// machine: "cart" ("workflows/Flows.ts"), key "cart"
// scenario: "happy-path" - "Happy path"
// route: open → sent
// machine-hash: sha256:72ebc97ad7ccde8474ffb0481c1c5169fe11f67782ff9a27df7bb840163ab63d
// scenario-hash: sha256:8466e78e3e1f6088ae155ef92460e97b3044e6cf98a452accccb199e3a18e2d3

// Given the flow starts in *open*
// When "submit" happens
// Then the flow moves to *sent*
// And the flow ends — *sent* is an end state

import { test, expect, type Page } from '@playwright/test';

const START_URL: string | null = "/shop";
const MACHINE = "cart";

const harness = (selector: string, why: string) =>
  new Error(
    `Test harness problem, not a bug in the page: the test harness expected ${selector}. ` +
      `${why} Construct binds workflow events to elements by convention (data-testid = the event name in kebab-case; ` +
      `data-flow / data-flow-state on the element that shows the machine's state). ` +
      `Add the attribute (or scaffold the page with \`construct create page --from\`); do not file a product bug for this.`,
  );

async function required(page: Page, selector: string, why: string) {
  const el = page.locator(selector).first();
  try {
    await el.waitFor({ state: 'attached', timeout: 5_000 });
  } catch {
    throw harness(selector, why);
  }
  return el;
}

async function trigger(page: Page, testId: string, event: string) {
  const el = await required(page, `[data-testid="${testId}"]`, `It is what the workflow event ${event} binds to.`);
  await el.click();
}

async function expectFlowState(page: Page, machine: string, state: string, timeout = 5_000) {
  const el = await required(page, `[data-flow="${machine}"][data-flow-state]`, `It shows the state of the ${machine} workflow.`);
  await expect(el).toHaveAttribute('data-flow-state', state, { timeout });
}

test("shop / cart / Happy path", async ({ page }) => {
  if (START_URL === null) return;
  await page.goto(START_URL);
  await expectFlowState(page, MACHINE, "open");
  // When "submit" happens
  await trigger(page, "cart-submit", "SUBMIT");
  await expectFlowState(page, MACHINE, "sent");
});
