// @construct-generated tests v1 - LOCKED, do not edit (#348)
// Generated by `construct generate tests`. Regenerated whenever the workflow changes; edits are refused.
// To change it: clone it to features/shop/tests/ (one level up), where nothing regenerates it.
// feature: "shop"
// machine: "review" ("workflows/Flows.ts"), key "review"
// scenario: "happy-path" - "Happy path"
// route: drafting → reviewing → approved
// machine-hash: sha256:f0c710b81151a2911a8c5b5b32d84ce7c74eb282005d2780217715e015b71e4e
// scenario-hash: sha256:1e77049c06e58442742438b70b1c97c322f0e283909400f3acd5c92cfcbe8861

// Given the flow starts in *drafting*
// When "submit" happens
// Then the flow moves to *reviewing*
// And when "approve" happens
// Then the flow moves to *approved*
// And the flow ends — *approved* is an end state
// Note: in *drafting* the flow can start that step over when "save" happens, so this part can repeat.

import { test, expect, type Page } from '@playwright/test';

const START_URL: string | null = "/shop";
const MACHINE = "review";

const harness = (selector: string, why: string) =>
  new Error(
    `Test harness problem, not a bug in the page: the test harness expected ${selector}. ` +
      `${why} Construct binds workflow events to elements by convention (data-testid = the event name in kebab-case; ` +
      `data-flow / data-flow-state on the element that shows the machine's state). ` +
      `Add the attribute (or scaffold the page with \`construct create page --from\`); do not file a product bug for this.`,
  );

async function required(page: Page, selector: string, why: string) {
  const el = page.locator(selector).first();
  try {
    await el.waitFor({ state: 'attached', timeout: 5_000 });
  } catch {
    throw harness(selector, why);
  }
  return el;
}

async function trigger(page: Page, testId: string, event: string) {
  const el = await required(page, `[data-testid="${testId}"]`, `It is what the workflow event ${event} binds to.`);
  await el.click();
}

async function expectFlowState(page: Page, machine: string, state: string, timeout = 5_000) {
  const el = await required(page, `[data-flow="${machine}"][data-flow-state]`, `It shows the state of the ${machine} workflow.`);
  await expect(el).toHaveAttribute('data-flow-state', state, { timeout });
}

test("shop / review / Happy path", async ({ page }) => {
  if (START_URL === null) return;
  await page.goto(START_URL);
  await expectFlowState(page, MACHINE, "drafting");
  // When "submit" happens
  await trigger(page, "review-submit", "SUBMIT");
  await expectFlowState(page, MACHINE, "reviewing");
  // When "approve" happens
  await trigger(page, "approve", "APPROVE");
  await expectFlowState(page, MACHINE, "approved");
});
