// Domain layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Pure functions only: no network, storage or DOM.

export function asText(v) {
  return String(v);
}

// Rows for the "contacts" list.
export function toContactRows(items) {
  return items.map((item) => ({
    id: item.id,
    email: asText(item.email),
    city: asText(item.city),
  }));
}

// "contactCount" = count. Design showed "3".
export function contactCount(items) {
  return asText(items.length);
}

export function findContact(items, id) {
  return items.find((item) => item.id === id) ?? null;
}

// Form text -> the types the API expects (taken from the example request body).
export function toContactInput(values) {
  return {
    first: String(values.first ?? "").trim(),
    last: String(values.last ?? "").trim(),
    email: String(values.email ?? "").trim(),
    city: String(values.city ?? "").trim(),
  };
}

// Raw values to prefill the form when an item is selected.
export function toFormValues(item) {
  if (!item) return {};
  return {
    first: item.first,
    last: item.last,
    email: item.email,
    city: item.city,
  };
}
