// Page layer — generated by line-matcher from the design. Props in, JSX out; no business logic.
import CategoryRow from "../component/CategoryRow.jsx";

export default function CategoriesPage({
  status,
  error,
  categoryCount,
  totalSpend,
  largestSpend,
  refreshedAt,
  rows,
  selectedId,
  formValues,
  onEdit,
  onDelete,
  onSave,
  onCancel,
}) {
  return (
    <main className="page">
      {status === "loading" && <p className="status">Loading…</p>}
      {error && (
        <p role="alert" className="error">
          {error}
        </p>
      )}
      <header className="header">
        <h1>My categories</h1>
        <p className="meta">
          <span>{categoryCount}</span> categories · <span>{totalSpend}</span> total spend · largest{" "}
          <span>{largestSpend}</span> · refreshed <span>{refreshedAt}</span>
        </p>
      </header>

      <form
        className="card form"
        key={selectedId ?? "new"}
        onSubmit={(e) => {
          e.preventDefault();
          onSave(Object.fromEntries(new FormData(e.currentTarget)));
        }}
      >
        <input
          name="name"
          placeholder="Category name"
          required
          defaultValue={formValues.name ?? ""}
        />
        <input
          name="spend"
          type="number"
          placeholder="Spend (USD)"
          required
          defaultValue={formValues.spend ?? ""}
        />
        <input name="owner" placeholder="Owner" required defaultValue={formValues.owner ?? ""} />
        <button type="submit" className="primary">
          Save
        </button>
        <button type="button" onClick={onCancel}>
          Cancel
        </button>
      </form>

      <table className="card table">
        <thead>
          <tr>
            <th>Category</th>
            <th>Spend</th>
            <th>Owner</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <CategoryRow
              key={row.id}
              row={row}
              selected={row.id === selectedId}
              onEdit={onEdit}
              onDelete={onDelete}
            />
          ))}
        </tbody>
      </table>
    </main>
  );
}
