// Domain layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Pure functions only: no network, storage or DOM.

export function asText(v) {
  return String(v);
}

export function moneyCompact(v) {
  const n = Number(v);
  const units = [
    [1e9, "B"],
    [1e6, "M"],
    [1e3, "K"],
  ];
  for (const [size, suffix] of units) {
    if (Math.abs(n) >= size) return "$" + (n / size).toFixed(1) + suffix;
  }
  return "$" + n.toFixed(0);
}

export function dateShort(v) {
  const d = new Date(v);
  const m = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return d.getUTCDate() + " " + m[d.getUTCMonth()] + " " + d.getUTCFullYear();
}

// Rows for the "invoices" list, sort by amount descending.
export function toInvoiceRows(items) {
  return [...items]
    .sort((a, b) => {
      const x = a.amount,
        y = b.amount;
      const c =
        typeof x === "number" && typeof y === "number" ? x - y : String(x).localeCompare(String(y));
      return -c;
    })
    .map((item) => ({
      id: item.id,
      number: asText(item.number),
      vendor: asText(item.vendor),
      amount: moneyCompact(item.amount),
      dueDate: dateShort(item.dueDate),
    }));
}

// "invoiceCount" = count. Design showed "4".
export function invoiceCount(items) {
  return asText(items.length);
}

// "totalBilled" = sum(amount), shown as moneyCompact. Design showed "$107.9M".
export function totalBilled(items) {
  return moneyCompact(items.reduce((s, x) => s + Number(x.amount), 0));
}

export function findInvoice(items, id) {
  return items.find((item) => item.id === id) ?? null;
}

// Form text -> the types the API expects (taken from the example request body).
export function toInvoiceInput(values) {
  return {
    vendor: String(values.vendor ?? "").trim(),
    amount: Number(values.amount),
    requester: String(values.requester ?? "").trim(),
  };
}

// Raw values to prefill the form when an item is selected.
export function toFormValues(item) {
  if (!item) return {};
  return {
    vendor: item.vendor,
    amount: item.amount,
    requester: item.requester,
  };
}
