// Service layer — generated by line-matcher. Do not add logic that belongs to another layer.
// External I/O only: one function per API endpoint.

async function request(method, url, body) {
  const res = await fetch(url, {
    method,
    headers: body ? { "Content-Type": "application/json" } : undefined,
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) throw new Error(`${method} ${url} failed with ${res.status}`);
  return res.status === 204 ? null : res.json();
}

export const listInvoices = () => request("GET", `/api/invoices`);
export const createInvoice = (data) => request("POST", `/api/invoices`, data);
export const updateInvoice = (id, data) =>
  request("PUT", `/api/invoices/${encodeURIComponent(id)}`, data);
export const deleteInvoice = (id) => request("DELETE", `/api/invoices/${encodeURIComponent(id)}`);
