// Route layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Navigation entry point. Delegates to the controller.
import OrdersController from "../controller/OrdersController.jsx";

export const path = "/orders";

export default function OrdersRoute() {
  return <OrdersController />;
}
