// Route layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Navigation entry point. Delegates to the controller.
import CategoriesController from "../controller/CategoriesController.jsx";

export const path = "/categories";

export default function CategoriesRoute() {
  return <CategoriesController />;
}
