// Page layer — generated by line-matcher from the design. Props in, JSX out; no business logic.
import PortfolioFigma1Row from "../component/PortfolioFigma1Row.jsx";

export default function PortfolioFigma1Page({
  status,
  error,
  categoryCount,
  spendYouManage,
  refreshedAt,
  headline,
  improving,
  declining,
  spendCard,
  spendYoy,
  largestName,
  largestShare,
  savingsCard,
  acceptedPct,
  acceptedCount,
  resilienceTotal,
  impactHigh,
  impactMedium,
  impactLow,
  highCategories,
  savingsCount,
  savingsTarget,
  oldestDays,
  riskCount,
  riskCategories,
  riskTarget,
  rows,
  selectedId,
  onOpen,
  onSuggest,
}) {
  return (
    <main className="page">
      {status === "loading" && <p className="status">Loading…</p>}
      {error && (
        <p role="alert" className="error">
          {error}
        </p>
      )}
      <nav className="crumbs">Health / My Portfolio</nav>
      <header className="header">
        <h1>My Portfolio</h1>
        <p className="meta">
          {"Your categories "}
          <span>{categoryCount}</span>
          {" · Spend you manage "}
          <span>{spendYouManage}</span>
          {" · Refreshed "}
          <span>{refreshedAt}</span>
        </p>
      </header>

      <section className="card">
        <p className="kicker">MAX · Your portfolio summary</p>
        <h2>
          <span>{headline}</span>
        </h2>
        <p>
          {"Improving: "}
          <span>{improving}</span>
        </p>
        <p>
          {"Declining: "}
          <span>{declining}</span>
        </p>
      </section>

      <h2>Your portfolio at a glance</h2>
      <div className="cards">
        <div className="card metric">
          <p className="label">Spend you manage · T12M</p>
          <p className="big">
            <span>{spendCard}</span>
          </p>
          <p>
            <span>{spendYoy}</span>
          </p>
          <p className="note">
            {"Across the six categories assigned to you. "}
            <span>{largestName}</span>
            {" is "}
            <span>{largestShare}</span>
            {" of it."}
          </p>
        </div>
        <div className="card metric">
          <p className="label">Savings potential</p>
          <p className="big">
            <span>{savingsCard}</span>
          </p>
          <p>
            <span>{acceptedPct}</span>
            {" of qualified savings initiatives accepted"}
          </p>
          <p className="note">
            {"Sum of the mid-point estimate from each of your six categories. "}
            <span>{acceptedCount}</span>
            {" qualified initiatives have been accepted."}
          </p>
        </div>
        <div className="card metric">
          <p className="label">Resilience based initiatives</p>
          <p className="big">
            <span>{resilienceTotal}</span>
          </p>
          <p>
            <span>{impactHigh}</span>
            {" high · "}
            <span>{impactMedium}</span>
            {" medium · "}
            <span>{impactLow}</span>
            {" low."}
          </p>
          <p className="note">
            <span>{highCategories}</span>
            {" categories carry at least one high."}
          </p>
        </div>
        <div className="card metric">
          <p className="label">Number of savings initiatives</p>
          <p className="big">
            <span>{savingsCount}</span>
          </p>
          <p>
            {"target "}
            <span>{savingsTarget}</span>
          </p>
          <p className="note">
            {
              "Savings initiatives raised but not yet accepted by an owner. Oldest has been waiting "
            }
            <span>{oldestDays}</span>
            {" days."}
          </p>
        </div>
        <div className="card metric">
          <p className="label">Risk initiatives</p>
          <p className="big">
            <span>{riskCount}</span>
          </p>
          <p>
            {"resilience initiatives · "}
            <span>{riskCategories}</span>
            {" categories"}
          </p>
          <p className="note">
            {"target "}
            <span>{riskTarget}</span>
          </p>
        </div>
      </div>

      <div className="card">
        <p>Ask Anything about your portfolio</p>
        <button onClick={onSuggest}>Prompt suggestion 01</button>
        <button onClick={onSuggest}>Prompt suggestion 02</button>
      </div>

      <h2>Category overview</h2>
      <p className="meta">
        Order based on top spend categories (Top 10) within that ordered by the ones needing max
        attention. Open any row for the full scorecard.
      </p>
      <table className="card table">
        <thead>
          <tr>
            <th>#</th>
            <th>Category</th>
            <th>Spend</th>
            <th>Maturity</th>
            <th>Savings potential</th>
            <th>Needs attention</th>
            <th>Trend</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <PortfolioFigma1Row
              key={row.id}
              row={row}
              selected={row.id === selectedId}
              onOpen={onOpen}
            />
          ))}
        </tbody>
      </table>
    </main>
  );
}
