// Page layer — generated by line-matcher from the design. Props in, JSX out; no business logic.
import RosterRow from "../component/RosterRow.jsx";

export default function RosterPage({
  status,
  error,
  projectCount,
  plannedTotal,
  forecastTotal,
  rows,
  selectedId,
  formValues,
  onEdit,
  onDelete,
  onSave,
  onCancel,
}) {
  return (
    <main className="page">
      {status === "loading" && <p className="status">Loading…</p>}
      {error && (
        <p role="alert" className="error">
          {error}
        </p>
      )}
      <header className="header">
        <h1>Roster</h1>
        <p className="meta">
          <span>{projectCount}</span>
          {" projects · planned "}
          <span>{plannedTotal}</span>
          {" · forecast "}
          <span>{forecastTotal}</span>
        </p>
      </header>

      <form
        className="card form"
        key={selectedId ?? "new"}
        onSubmit={(e) => {
          e.preventDefault();
          onSave(Object.fromEntries(new FormData(e.currentTarget)));
        }}
      >
        <input
          name="project"
          placeholder="Project"
          required
          defaultValue={formValues.project ?? ""}
        />
        <input name="lead" placeholder="Lead" required defaultValue={formValues.lead ?? ""} />
        <input name="deputy" placeholder="Deputy" required defaultValue={formValues.deputy ?? ""} />
        <button type="submit" className="primary">
          Save
        </button>
        <button type="button" onClick={onCancel}>
          Cancel
        </button>
      </form>

      <table className="card table">
        <thead>
          <tr>
            <th>Project</th>
            <th>Owner</th>
            <th>Backup</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <RosterRow
              key={row.id}
              row={row}
              selected={row.id === selectedId}
              onEdit={onEdit}
              onDelete={onDelete}
            />
          ))}
        </tbody>
      </table>
    </main>
  );
}
