// Component layer — generated by line-matcher. Reusable presentation only.
export default function OrderRow({ row, selected, onEdit, onDelete }) {
  return (
    <tr data-selected={selected ? "true" : undefined}>
      <td>{row.number}</td>
      <td>{row.customer}</td>
      <td className="num">{row.total}</td>
      <td>{row.placedOn}</td>
      <td>{row.status}</td>
      <td className="actions">
        <button onClick={() => onEdit(row.id)}>Edit</button>
        <button className="danger" onClick={() => onDelete(row.id)}>
          Delete
        </button>
      </td>
    </tr>
  );
}
