module.exports = {
  // ...
  darkMode: "selector",

  theme: {
    extend: {
      colors: {
        "brand-primary": "var(--color-brand-primary)",
        "default-font": "var(--color-default-font)",
        "subtext-color": "var(--color-subtext-color)",
        "neutral-border": "var(--color-neutral-border)",
        white: "var(--color-white)",
        "white-alt": "var(--color-white-alt)",
        "default-background": "var(--color-default-background)",
        "bg-white-alt": "var(--color-bg-white-alt)",
        "brand-25": "var(--color-brand-25)",
        "brand-50": "var(--color-brand-50)",
        "brand-100": "var(--color-brand-100)",
        "brand-200": "var(--color-brand-200)",
        "brand-300": "var(--color-brand-300)",
        "brand-400": "var(--color-brand-400)",
        "brand-500": "var(--color-brand-500)",
        "brand-600": "var(--color-brand-600)",
        "brand-700": "var(--color-brand-700)",
        "brand-800": "var(--color-brand-800)",
        "brand-900": "var(--color-brand-900)",
        "brand-950": "var(--color-brand-950)",
        "neutral-0": "var(--color-neutral-0)",
        "neutral-50": "var(--color-neutral-50)",
        "neutral-100": "var(--color-neutral-100)",
        "neutral-200": "var(--color-neutral-200)",
        "neutral-300": "var(--color-neutral-300)",
        "neutral-400": "var(--color-neutral-400)",
        "neutral-500": "var(--color-neutral-500)",
        "neutral-600": "var(--color-neutral-600)",
        "neutral-700": "var(--color-neutral-700)",
        "neutral-800": "var(--color-neutral-800)",
        "neutral-900": "var(--color-neutral-900)",
        "neutral-950": "var(--color-neutral-950)",
        "error-50": "var(--color-error-50)",
        "error-100": "var(--color-error-100)",
        "error-200": "var(--color-error-200)",
        "error-300": "var(--color-error-300)",
        "error-400": "var(--color-error-400)",
        "error-500": "var(--color-error-500)",
        "error-600": "var(--color-error-600)",
        "error-700": "var(--color-error-700)",
        "error-800": "var(--color-error-800)",
        "error-900": "var(--color-error-900)",
        "warning-50": "var(--color-warning-50)",
        "warning-100": "var(--color-warning-100)",
        "warning-200": "var(--color-warning-200)",
        "warning-300": "var(--color-warning-300)",
        "warning-400": "var(--color-warning-400)",
        "warning-500": "var(--color-warning-500)",
        "warning-600": "var(--color-warning-600)",
        "warning-700": "var(--color-warning-700)",
        "warning-800": "var(--color-warning-800)",
        "warning-900": "var(--color-warning-900)",
        "success-50": "var(--color-success-50)",
        "success-100": "var(--color-success-100)",
        "success-200": "var(--color-success-200)",
        "success-300": "var(--color-success-300)",
        "success-400": "var(--color-success-400)",
        "success-500": "var(--color-success-500)",
        "success-600": "var(--color-success-600)",
        "success-700": "var(--color-success-700)",
        "success-800": "var(--color-success-800)",
        "success-900": "var(--color-success-900)",
        "blue-50": "var(--color-blue-50)",
        "blue-100": "var(--color-blue-100)",
        "blue-200": "var(--color-blue-200)",
        "blue-300": "var(--color-blue-300)",
        "blue-400": "var(--color-blue-400)",
        "blue-500": "var(--color-blue-500)",
        "blue-600": "var(--color-blue-600)",
        "blue-700": "var(--color-blue-700)",
        "blue-800": "var(--color-blue-800)",
        "blue-900": "var(--color-blue-900)",
        "cyan-50": "var(--color-cyan-50)",
        "cyan-100": "var(--color-cyan-100)",
        "cyan-200": "var(--color-cyan-200)",
        "cyan-300": "var(--color-cyan-300)",
        "cyan-400": "var(--color-cyan-400)",
        "cyan-500": "var(--color-cyan-500)",
        "cyan-600": "var(--color-cyan-600)",
        "cyan-700": "var(--color-cyan-700)",
        "cyan-800": "var(--color-cyan-800)",
        "cyan-900": "var(--color-cyan-900)",
        "pink-50": "var(--color-pink-50)",
        "pink-100": "var(--color-pink-100)",
        "pink-200": "var(--color-pink-200)",
        "pink-300": "var(--color-pink-300)",
        "pink-400": "var(--color-pink-400)",
        "pink-500": "var(--color-pink-500)",
        "pink-600": "var(--color-pink-600)",
        "pink-700": "var(--color-pink-700)",
        "pink-800": "var(--color-pink-800)",
        "pink-900": "var(--color-pink-900)",
        "alpha-slate-80": "var(--color-alpha-slate-80)",
        "alpha-white-80": "var(--color-alpha-white-80)",
        "orange-50": "var(--color-orange-50)",
        "orange-100": "var(--color-orange-100)",
        "orange-200": "var(--color-orange-200)",
        "orange-300": "var(--color-orange-300)",
        "orange-400": "var(--color-orange-400)",
        "orange-500": "var(--color-orange-500)",
        "orange-600": "var(--color-orange-600)",
        "orange-700": "var(--color-orange-700)",
        "orange-800": "var(--color-orange-800)",
        "orange-900": "var(--color-orange-900)",
        "purple-50": "var(--color-purple-50)",
        "purple-100": "var(--color-purple-100)",
        "purple-200": "var(--color-purple-200)",
        "purple-300": "var(--color-purple-300)",
        "purple-400": "var(--color-purple-400)",
        "purple-500": "var(--color-purple-500)",
        "purple-600": "var(--color-purple-600)",
        "purple-700": "var(--color-purple-700)",
        "purple-800": "var(--color-purple-800)",
        "purple-900": "var(--color-purple-900)",
        "lemon-50": "var(--color-lemon-50)",
        "lemon-100": "var(--color-lemon-100)",
        "lemon-200": "var(--color-lemon-200)",
        "lemon-300": "var(--color-lemon-300)",
        "lemon-400": "var(--color-lemon-400)",
        "lemon-500": "var(--color-lemon-500)",
        "lemon-600": "var(--color-lemon-600)",
        "lemon-700": "var(--color-lemon-700)",
        "lemon-800": "var(--color-lemon-800)",
        "lemon-900": "var(--color-lemon-900)",
        "fuchsia-50": "var(--color-fuchsia-50)",
        "fuchsia-100": "var(--color-fuchsia-100)",
        "fuchsia-200": "var(--color-fuchsia-200)",
        "fuchsia-300": "var(--color-fuchsia-300)",
        "fuchsia-400": "var(--color-fuchsia-400)",
        "fuchsia-500": "var(--color-fuchsia-500)",
        "fuchsia-600": "var(--color-fuchsia-600)",
        "fuchsia-700": "var(--color-fuchsia-700)",
        "fuchsia-800": "var(--color-fuchsia-800)",
        "fuchsia-900": "var(--color-fuchsia-900)",
        "accent-default-aqua": "var(--color-accent-default-aqua)",
        "accent-default-bumble-bee": "var(--color-accent-default-bumble-bee)",
        "accent-default-fuchsia": "var(--color-accent-default-fuchsia)",
        "accent-default-midnight": "var(--color-accent-default-midnight)",
        "accent-soft-aqua": "var(--color-accent-soft-aqua)",
        "accent-soft-fuchsia": "var(--color-accent-soft-fuchsia)",
        "accent-soft-midnight": "var(--color-accent-soft-midnight)",
        "accent-soft-bumble-bee": "var(--color-accent-soft-bumble-bee)",
        "accent-vivid-aqua": "var(--color-accent-vivid-aqua)",
        "accent-vivid-bumble-bee": "var(--color-accent-vivid-bumble-bee)",
        "accent-vivid-fuchsia": "var(--color-accent-vivid-fuchsia)",
        "accent-vivid-midnight": "var(--color-accent-vivid-midnight)",
        "accent-default-indigo": "var(--color-accent-default-indigo)",
        "accent-soft-indigo": "var(--color-accent-soft-indigo)",
        "accent-vivid-indigo": "var(--color-accent-vivid-indigo)",
        "bg-01": "var(--color-bg-01)",
        "bg-white": "var(--color-bg-white)",
        "alpha-brand-0": "var(--color-alpha-brand-0)",
        "alpha-brand-4": "var(--color-alpha-brand-4)",
        "alpha-brand-8": "var(--color-alpha-brand-8)",
        "alpha-brand-12": "var(--color-alpha-brand-12)",
        "alpha-brand-16": "var(--color-alpha-brand-16)",
        "alpha-brand-24": "var(--color-alpha-brand-24)",
        "alpha-brand-32": "var(--color-alpha-brand-32)",
        "alpha-brand-48": "var(--color-alpha-brand-48)",
        "alpha-brand-64": "var(--color-alpha-brand-64)",
        "alpha-brand-80": "var(--color-alpha-brand-80)",
        "alpha-brand-96": "var(--color-alpha-brand-96)",
        "alpha-brand-100": "var(--color-alpha-brand-100)",
        "alpha-slate-0": "var(--color-alpha-slate-0)",
        "alpha-slate-4": "var(--color-alpha-slate-4)",
        "alpha-slate-8": "var(--color-alpha-slate-8)",
        "alpha-slate-12": "var(--color-alpha-slate-12)",
        "alpha-slate-16": "var(--color-alpha-slate-16)",
        "alpha-slate-24": "var(--color-alpha-slate-24)",
        "alpha-slate-32": "var(--color-alpha-slate-32)",
        "alpha-slate-48": "var(--color-alpha-slate-48)",
        "alpha-slate-64": "var(--color-alpha-slate-64)",
        "alpha-slate-96": "var(--color-alpha-slate-96)",
        "alpha-slate-100": "var(--color-alpha-slate-100)",
        "alpha-white-0": "var(--color-alpha-white-0)",
        "alpha-white-4": "var(--color-alpha-white-4)",
        "alpha-white-8": "var(--color-alpha-white-8)",
        "alpha-white-12": "var(--color-alpha-white-12)",
        "alpha-white-16": "var(--color-alpha-white-16)",
        "alpha-white-24": "var(--color-alpha-white-24)",
        "alpha-white-32": "var(--color-alpha-white-32)",
        "alpha-white-48": "var(--color-alpha-white-48)",
        "alpha-white-64": "var(--color-alpha-white-64)",
        "alpha-white-96": "var(--color-alpha-white-96)",
        "alpha-white-100": "var(--color-alpha-white-100)",
        "alpha-shadow-4": "var(--color-alpha-shadow-4)",
        "alpha-shadow-8": "var(--color-alpha-shadow-8)",
        "alpha-shadow-12": "var(--color-alpha-shadow-12)",
        "alpha-shadow-16": "var(--color-alpha-shadow-16)",
        "alpha-shadow-24": "var(--color-alpha-shadow-24)",
        "alpha-shadow-32": "var(--color-alpha-shadow-32)",
        "alpha-shadow-48": "var(--color-alpha-shadow-48)",
        "alpha-shadow-64": "var(--color-alpha-shadow-64)",
        "alpha-shadow-80": "var(--color-alpha-shadow-80)",
        "alpha-shadow-96": "var(--color-alpha-shadow-96)",
        "alpha-shadow-100": "var(--color-alpha-shadow-100)",
        "alpha-error-0": "var(--color-alpha-error-0)",
        "alpha-error-4": "var(--color-alpha-error-4)",
        "alpha-error-8": "var(--color-alpha-error-8)",
        "alpha-error-12": "var(--color-alpha-error-12)",
        "alpha-error-16": "var(--color-alpha-error-16)",
        "alpha-error-24": "var(--color-alpha-error-24)",
        "alpha-error-32": "var(--color-alpha-error-32)",
        "alpha-error-48": "var(--color-alpha-error-48)",
        "alpha-error-64": "var(--color-alpha-error-64)",
        "alpha-error-80": "var(--color-alpha-error-80)",
        "alpha-error-96": "var(--color-alpha-error-96)",
        "alpha-error-100": "var(--color-alpha-error-100)",
        "alpha-success-0": "var(--color-alpha-success-0)",
        "alpha-success-4": "var(--color-alpha-success-4)",
        "alpha-success-8": "var(--color-alpha-success-8)",
        "alpha-success-12": "var(--color-alpha-success-12)",
        "alpha-success-16": "var(--color-alpha-success-16)",
        "alpha-success-24": "var(--color-alpha-success-24)",
        "alpha-success-32": "var(--color-alpha-success-32)",
        "alpha-success-48": "var(--color-alpha-success-48)",
        "alpha-success-64": "var(--color-alpha-success-64)",
        "alpha-success-80": "var(--color-alpha-success-80)",
        "alpha-success-96": "var(--color-alpha-success-96)",
        "alpha-success-100": "var(--color-alpha-success-100)",
        "alpha-warning-0": "var(--color-alpha-warning-0)",
        "alpha-warning-4": "var(--color-alpha-warning-4)",
        "alpha-warning-8": "var(--color-alpha-warning-8)",
        "alpha-warning-12": "var(--color-alpha-warning-12)",
        "alpha-warning-16": "var(--color-alpha-warning-16)",
        "alpha-warning-24": "var(--color-alpha-warning-24)",
        "alpha-warning-32": "var(--color-alpha-warning-32)",
        "alpha-warning-48": "var(--color-alpha-warning-48)",
        "alpha-warning-64": "var(--color-alpha-warning-64)",
        "alpha-warning-80": "var(--color-alpha-warning-80)",
        "alpha-warning-96": "var(--color-alpha-warning-96)",
        "alpha-warning-100": "var(--color-alpha-warning-100)",
        "alpha-aqua-0": "var(--color-alpha-aqua-0)",
        "alpha-aqua-8": "var(--color-alpha-aqua-8)",
        "alpha-aqua-4": "var(--color-alpha-aqua-4)",
        "alpha-aqua-12": "var(--color-alpha-aqua-12)",
        "alpha-aqua-16": "var(--color-alpha-aqua-16)",
        "alpha-aqua-24": "var(--color-alpha-aqua-24)",
        "alpha-aqua-32": "var(--color-alpha-aqua-32)",
        "alpha-aqua-48": "var(--color-alpha-aqua-48)",
        "alpha-aqua-64": "var(--color-alpha-aqua-64)",
        "alpha-aqua-80": "var(--color-alpha-aqua-80)",
        "alpha-aqua-96": "var(--color-alpha-aqua-96)",
        "alpha-aqua-100": "var(--color-alpha-aqua-100)",
        "alpha-fuchsia-0": "var(--color-alpha-fuchsia-0)",
        "alpha-fuchsia-4": "var(--color-alpha-fuchsia-4)",
        "alpha-fuchsia-8": "var(--color-alpha-fuchsia-8)",
        "alpha-fuchsia-12": "var(--color-alpha-fuchsia-12)",
        "alpha-fuchsia-16": "var(--color-alpha-fuchsia-16)",
        "alpha-fuchsia-24": "var(--color-alpha-fuchsia-24)",
        "alpha-fuchsia-32": "var(--color-alpha-fuchsia-32)",
        "alpha-fuchsia-48": "var(--color-alpha-fuchsia-48)",
        "alpha-fuchsia-64": "var(--color-alpha-fuchsia-64)",
        "alpha-fuchsia-80": "var(--color-alpha-fuchsia-80)",
        "alpha-fuchsia-96": "var(--color-alpha-fuchsia-96)",
        "alpha-fuchsia-100": "var(--color-alpha-fuchsia-100)",
        "data-viz-categorical-01": "var(--color-data-viz-categorical-01)",
        "data-viz-categorical-02": "var(--color-data-viz-categorical-02)",
        "data-viz-categorical-03": "var(--color-data-viz-categorical-03)",
        "data-viz-categorical-04": "var(--color-data-viz-categorical-04)",
        "data-viz-categorical-05": "var(--color-data-viz-categorical-05)",
        "data-viz-diverging-01": "var(--color-data-viz-diverging-01)",
        "data-viz-diverging-02": "var(--color-data-viz-diverging-02)",
        "data-viz-diverging-03": "var(--color-data-viz-diverging-03)",
        "data-viz-diverging-04": "var(--color-data-viz-diverging-04)",
        "data-viz-diverging-05": "var(--color-data-viz-diverging-05)",
        "data-viz-diverging-06": "var(--color-data-viz-diverging-06)",
        "data-viz-diverging-07": "var(--color-data-viz-diverging-07)",
        "data-viz-diverging-08": "var(--color-data-viz-diverging-08)",
        "data-viz-diverging-09": "var(--color-data-viz-diverging-09)",
        "data-viz-sequential-01": "var(--color-data-viz-sequential-01)",
        "data-viz-sequential-02": "var(--color-data-viz-sequential-02)",
        "data-viz-sequential-03": "var(--color-data-viz-sequential-03)",
        "data-viz-sequential-04": "var(--color-data-viz-sequential-04)",
        "data-viz-sequential-05": "var(--color-data-viz-sequential-05)",
      },
      fontSize: {
        caption: [
          "var(--text-caption)",
          {
            lineHeight: "var(--text-caption--line-height)",
            fontWeight: "var(--text-caption--font-weight)",
            letterSpacing: "var(--text-caption--letter-spacing)",
          },
        ],
        "body-2": [
          "var(--text-body-2)",
          {
            lineHeight: "var(--text-body-2--line-height)",
            fontWeight: "var(--text-body-2--font-weight)",
            letterSpacing: "var(--text-body-2--letter-spacing)",
          },
        ],
        "body-2-bold": [
          "var(--text-body-2-bold)",
          {
            lineHeight: "var(--text-body-2-bold--line-height)",
            fontWeight: "var(--text-body-2-bold--font-weight)",
            letterSpacing: "var(--text-body-2-bold--letter-spacing)",
          },
        ],
        "body-1": [
          "var(--text-body-1)",
          {
            lineHeight: "var(--text-body-1--line-height)",
            fontWeight: "var(--text-body-1--font-weight)",
            letterSpacing: "var(--text-body-1--letter-spacing)",
          },
        ],
        button: [
          "var(--text-button)",
          {
            lineHeight: "var(--text-button--line-height)",
            fontWeight: "var(--text-button--font-weight)",
            letterSpacing: "var(--text-button--letter-spacing)",
          },
        ],
        overline: [
          "var(--text-overline)",
          {
            lineHeight: "var(--text-overline--line-height)",
            fontWeight: "var(--text-overline--font-weight)",
            letterSpacing: "var(--text-overline--letter-spacing)",
          },
        ],
        "overline-xs": [
          "var(--text-overline-xs)",
          {
            lineHeight: "var(--text-overline-xs--line-height)",
            fontWeight: "var(--text-overline-xs--font-weight)",
            letterSpacing: "var(--text-overline-xs--letter-spacing)",
          },
        ],
        "button-xs": [
          "var(--text-button-xs)",
          {
            lineHeight: "var(--text-button-xs--line-height)",
            fontWeight: "var(--text-button-xs--font-weight)",
            letterSpacing: "var(--text-button-xs--letter-spacing)",
          },
        ],
        "caption-xs": [
          "var(--text-caption-xs)",
          {
            lineHeight: "var(--text-caption-xs--line-height)",
            fontWeight: "var(--text-caption-xs--font-weight)",
            letterSpacing: "var(--text-caption-xs--letter-spacing)",
          },
        ],
        h1: [
          "var(--text-h1)",
          {
            lineHeight: "var(--text-h1--line-height)",
            fontWeight: "var(--text-h1--font-weight)",
            letterSpacing: "var(--text-h1--letter-spacing)",
          },
        ],
        h2: [
          "var(--text-h2)",
          {
            lineHeight: "var(--text-h2--line-height)",
            fontWeight: "var(--text-h2--font-weight)",
            letterSpacing: "var(--text-h2--letter-spacing)",
          },
        ],
        h3: [
          "var(--text-h3)",
          {
            lineHeight: "var(--text-h3--line-height)",
            fontWeight: "var(--text-h3--font-weight)",
            letterSpacing: "var(--text-h3--letter-spacing)",
          },
        ],
        h4: [
          "var(--text-h4)",
          {
            lineHeight: "var(--text-h4--line-height)",
            fontWeight: "var(--text-h4--font-weight)",
            letterSpacing: "var(--text-h4--letter-spacing)",
          },
        ],
        h5: [
          "var(--text-h5)",
          {
            lineHeight: "var(--text-h5--line-height)",
            fontWeight: "var(--text-h5--font-weight)",
            letterSpacing: "var(--text-h5--letter-spacing)",
          },
        ],
        h6: [
          "var(--text-h6)",
          {
            lineHeight: "var(--text-h6--line-height)",
            fontWeight: "var(--text-h6--font-weight)",
            letterSpacing: "var(--text-h6--letter-spacing)",
          },
        ],
        "subtitle-1": [
          "var(--text-subtitle-1)",
          {
            lineHeight: "var(--text-subtitle-1--line-height)",
            fontWeight: "var(--text-subtitle-1--font-weight)",
            letterSpacing: "var(--text-subtitle-1--letter-spacing)",
          },
        ],
        "subtitle-2": [
          "var(--text-subtitle-2)",
          {
            lineHeight: "var(--text-subtitle-2--line-height)",
            fontWeight: "var(--text-subtitle-2--font-weight)",
            letterSpacing: "var(--text-subtitle-2--letter-spacing)",
          },
        ],
        "body-2-semibold": [
          "var(--text-body-2-semibold)",
          {
            lineHeight: "var(--text-body-2-semibold--line-height)",
            fontWeight: "var(--text-body-2-semibold--font-weight)",
            letterSpacing: "var(--text-body-2-semibold--letter-spacing)",
          },
        ],
        "h1-max": [
          "var(--text-h1-max)",
          {
            lineHeight: "var(--text-h1-max--line-height)",
            fontWeight: "var(--text-h1-max--font-weight)",
            letterSpacing: "var(--text-h1-max--letter-spacing)",
          },
        ],
        "h2-max": [
          "var(--text-h2-max)",
          {
            lineHeight: "var(--text-h2-max--line-height)",
            fontWeight: "var(--text-h2-max--font-weight)",
            letterSpacing: "var(--text-h2-max--letter-spacing)",
          },
        ],
        "h3-max": [
          "var(--text-h3-max)",
          {
            lineHeight: "var(--text-h3-max--line-height)",
            fontWeight: "var(--text-h3-max--font-weight)",
            letterSpacing: "var(--text-h3-max--letter-spacing)",
          },
        ],
        "h4-max": [
          "var(--text-h4-max)",
          {
            lineHeight: "var(--text-h4-max--line-height)",
            fontWeight: "var(--text-h4-max--font-weight)",
            letterSpacing: "var(--text-h4-max--letter-spacing)",
          },
        ],
        "h5-max": [
          "var(--text-h5-max)",
          {
            lineHeight: "var(--text-h5-max--line-height)",
            fontWeight: "var(--text-h5-max--font-weight)",
            letterSpacing: "var(--text-h5-max--letter-spacing)",
          },
        ],
        "h6-max": [
          "var(--text-h6-max)",
          {
            lineHeight: "var(--text-h6-max--line-height)",
            fontWeight: "var(--text-h6-max--font-weight)",
            letterSpacing: "var(--text-h6-max--letter-spacing)",
          },
        ],
        "subtitle-1-max": [
          "var(--text-subtitle-1-max)",
          {
            lineHeight: "var(--text-subtitle-1-max--line-height)",
            fontWeight: "var(--text-subtitle-1-max--font-weight)",
            letterSpacing: "var(--text-subtitle-1-max--letter-spacing)",
          },
        ],
        "subtitle-2-max": [
          "var(--text-subtitle-2-max)",
          {
            lineHeight: "var(--text-subtitle-2-max--line-height)",
            fontWeight: "var(--text-subtitle-2-max--font-weight)",
            letterSpacing: "var(--text-subtitle-2-max--letter-spacing)",
          },
        ],
        "body-1-max": [
          "var(--text-body-1-max)",
          {
            lineHeight: "var(--text-body-1-max--line-height)",
            fontWeight: "var(--text-body-1-max--font-weight)",
            letterSpacing: "var(--text-body-1-max--letter-spacing)",
          },
        ],
        "body-2-max": [
          "var(--text-body-2-max)",
          {
            lineHeight: "var(--text-body-2-max--line-height)",
            fontWeight: "var(--text-body-2-max--font-weight)",
            letterSpacing: "var(--text-body-2-max--letter-spacing)",
          },
        ],
        "body-2-semibold-max": [
          "var(--text-body-2-semibold-max)",
          {
            lineHeight: "var(--text-body-2-semibold-max--line-height)",
            fontWeight: "var(--text-body-2-semibold-max--font-weight)",
            letterSpacing: "var(--text-body-2-semibold-max--letter-spacing)",
          },
        ],
        "button-max": [
          "var(--text-button-max)",
          {
            lineHeight: "var(--text-button-max--line-height)",
            fontWeight: "var(--text-button-max--font-weight)",
            letterSpacing: "var(--text-button-max--letter-spacing)",
          },
        ],
        "button-xs-max": [
          "var(--text-button-xs-max)",
          {
            lineHeight: "var(--text-button-xs-max--line-height)",
            fontWeight: "var(--text-button-xs-max--font-weight)",
            letterSpacing: "var(--text-button-xs-max--letter-spacing)",
          },
        ],
        "caption-max": [
          "var(--text-caption-max)",
          {
            lineHeight: "var(--text-caption-max--line-height)",
            fontWeight: "var(--text-caption-max--font-weight)",
            letterSpacing: "var(--text-caption-max--letter-spacing)",
          },
        ],
        "caption-xs-max": [
          "var(--text-caption-xs-max)",
          {
            lineHeight: "var(--text-caption-xs-max--line-height)",
            fontWeight: "var(--text-caption-xs-max--font-weight)",
            letterSpacing: "var(--text-caption-xs-max--letter-spacing)",
          },
        ],
        "overline-max": [
          "var(--text-overline-max)",
          {
            lineHeight: "var(--text-overline-max--line-height)",
            fontWeight: "var(--text-overline-max--font-weight)",
            letterSpacing: "var(--text-overline-max--letter-spacing)",
          },
        ],
        "overline-xs-max": [
          "var(--text-overline-xs-max)",
          {
            lineHeight: "var(--text-overline-xs-max--line-height)",
            fontWeight: "var(--text-overline-xs-max--font-weight)",
            letterSpacing: "var(--text-overline-xs-max--letter-spacing)",
          },
        ],
        "caption-mono": [
          "var(--text-caption-mono)",
          {
            lineHeight: "var(--text-caption-mono--line-height)",
            fontWeight: "var(--text-caption-mono--font-weight)",
            letterSpacing: "var(--text-caption-mono--letter-spacing)",
          },
        ],
        "overline-mono": [
          "var(--text-overline-mono)",
          {
            lineHeight: "var(--text-overline-mono--line-height)",
            fontWeight: "var(--text-overline-mono--font-weight)",
            letterSpacing: "var(--text-overline-mono--letter-spacing)",
          },
        ],
        "caption-xs-mono": [
          "var(--text-caption-xs-mono)",
          {
            lineHeight: "var(--text-caption-xs-mono--line-height)",
            fontWeight: "var(--text-caption-xs-mono--font-weight)",
            letterSpacing: "var(--text-caption-xs-mono--letter-spacing)",
          },
        ],
        "overline-xs-mono": [
          "var(--text-overline-xs-mono)",
          {
            lineHeight: "var(--text-overline-xs-mono--line-height)",
            fontWeight: "var(--text-overline-xs-mono--font-weight)",
            letterSpacing: "var(--text-overline-xs-mono--letter-spacing)",
          },
        ],
        "body-2-mono": [
          "var(--text-body-2-mono)",
          {
            lineHeight: "var(--text-body-2-mono--line-height)",
            fontWeight: "var(--text-body-2-mono--font-weight)",
            letterSpacing: "var(--text-body-2-mono--letter-spacing)",
          },
        ],
      },
      fontFamily: {
        caption: "var(--font-caption)",
        "body-2": "var(--font-body-2)",
        "body-2-bold": "var(--font-body-2-bold)",
        "body-1": "var(--font-body-1)",
        button: "var(--font-button)",
        overline: "var(--font-overline)",
        "overline-xs": "var(--font-overline-xs)",
        "button-xs": "var(--font-button-xs)",
        "caption-xs": "var(--font-caption-xs)",
        h1: "var(--font-h1)",
        h2: "var(--font-h2)",
        h3: "var(--font-h3)",
        h4: "var(--font-h4)",
        h5: "var(--font-h5)",
        h6: "var(--font-h6)",
        "subtitle-1": "var(--font-subtitle-1)",
        "subtitle-2": "var(--font-subtitle-2)",
        "body-2-semibold": "var(--font-body-2-semibold)",
        "h1-max": "var(--font-h1-max)",
        "h2-max": "var(--font-h2-max)",
        "h3-max": "var(--font-h3-max)",
        "h4-max": "var(--font-h4-max)",
        "h5-max": "var(--font-h5-max)",
        "h6-max": "var(--font-h6-max)",
        "subtitle-1-max": "var(--font-subtitle-1-max)",
        "subtitle-2-max": "var(--font-subtitle-2-max)",
        "body-1-max": "var(--font-body-1-max)",
        "body-2-max": "var(--font-body-2-max)",
        "body-2-semibold-max": "var(--font-body-2-semibold-max)",
        "button-max": "var(--font-button-max)",
        "button-xs-max": "var(--font-button-xs-max)",
        "caption-max": "var(--font-caption-max)",
        "caption-xs-max": "var(--font-caption-xs-max)",
        "overline-max": "var(--font-overline-max)",
        "overline-xs-max": "var(--font-overline-xs-max)",
        "caption-mono": "var(--font-caption-mono)",
        "overline-mono": "var(--font-overline-mono)",
        "caption-xs-mono": "var(--font-caption-xs-mono)",
        "overline-xs-mono": "var(--font-overline-xs-mono)",
        "body-2-mono": "var(--font-body-2-mono)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xs: "var(--shadow-xs)",
        xl: "var(--shadow-xl)",
        soft: "var(--shadow-soft)",
        "elevation---01": "var(--shadow-elevation---01)",
      },
      borderRadius: {
        "rounded-xs": "var(--radius-rounded-xs)",
        "rounded-md": "var(--radius-rounded-md)",
        "rounded-lg": "var(--radius-rounded-lg)",
        full: "var(--radius-full)",
        "rounded-sm": "var(--radius-rounded-sm)",
      },
      container: {
        padding: {
          DEFAULT: "16px",
          sm: "calc((100vw + 16px - 640px) / 2)",
          md: "calc((100vw + 16px - 768px) / 2)",
          lg: "calc((100vw + 16px - 1024px) / 2)",
          xl: "calc((100vw + 16px - 1280px) / 2)",
          "2xl": "calc((100vw + 16px - 1536px) / 2)",
        },
      },
      spacing: {
        112: "28rem",
        144: "36rem",
        192: "48rem",
        256: "64rem",
        320: "80rem",
      },
      screens: {
        tablet: {
          max: "1024px",
        },
        mobile: {
          max: "400px",
        },
      },
    },
  },
};
