// Domain layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Pure functions only: no network, storage or DOM.

// Reads a dotted path ("a.b.c") from the response.
const get = (o, path) => path.split(".").reduce((x, k) => x?.[k], o);

export function asText(v) {
  return String(v);
}

export function dateShort(v) {
  const d = new Date(v);
  const m = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return d.getUTCDate() + " " + m[d.getUTCMonth()] + " " + d.getUTCFullYear();
}

// Rows for the "portfolio-redesigned" list.
export function toPortfolioRedesignedRows(items) {
  return items.map((item) => ({
    id: item.beroe_l2_id,
    name: asText(item.display_name),
    risk: asText(item.risk_score),
  }));
}

// "refreshedAt" = the response field "meta.snapshot_date", shown as dateShort. Design showed "31 Jul 2026".
export function refreshedAt(data) {
  return dateShort(get(data, "meta.snapshot_date"));
}

// "headline" = the response field "narrative.cross_l2_summary". Design showed "Grains is carrying your portfolio. Logistics and Packaging are not.".
export function headline(data) {
  return asText(get(data, "narrative.cross_l2_summary"));
}

// TODO: "improving" (design showed "Grains, up on contract coverage and a renegotiated origination mix, and Chemicals, where the solvent index fell two quarters running.") was skipped in Q&A — decide where it comes from.
export function improving() {
  return "—";
}

// TODO: "declining" (design showed "Logistics, where the maturity gap widened to −0.7 and three high flags are open, and Packaging, where supplier concentration moved the wrong way. IT & Software is flat.") was skipped in Q&A — decide where it comes from.
export function declining() {
  return "—";
}

// TODO: "highCategories" (design showed "4") was skipped in Q&A — decide where it comes from.
export function highCategories() {
  return "—";
}

// TODO: "savingsRange" (design showed "$42 - 68M") was skipped in Q&A — decide where it comes from.
export function savingsRange() {
  return "—";
}

// TODO: "qualifiedCount" (design showed "25") was skipped in Q&A — decide where it comes from.
export function qualifiedCount() {
  return "—";
}

// "coveredCount" = the response field "portfolio_at_a_glance.resilience_initiatives.total". Design showed "21".
export function coveredCount(data) {
  return asText(get(data, "portfolio_at_a_glance.resilience_initiatives.total"));
}

// "resilienceTotal" = the response field "portfolio_at_a_glance.resilience_initiatives.total". Design showed "21".
export function resilienceTotal(data) {
  return asText(get(data, "portfolio_at_a_glance.resilience_initiatives.total"));
}

// "savingsCount" = the response field "portfolio_at_a_glance.waiting_on_decision.savings_count". Design showed "26".
export function savingsCount(data) {
  return asText(get(data, "portfolio_at_a_glance.waiting_on_decision.savings_count"));
}

// TODO: "oldestDays" (design showed "34") was skipped in Q&A — decide where it comes from.
export function oldestDays() {
  return "—";
}

// TODO: "qualifiedInitiatives" (design showed "16") was skipped in Q&A — decide where it comes from.
export function qualifiedInitiatives() {
  return "—";
}

export function findPortfolioRedesigned(items, id) {
  return items.find((item) => item.beroe_l2_id === id) ?? null;
}
