// Domain layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Pure functions only: no network, storage or DOM.

export function asText(v) {
  return String(v);
}

export function moneyCompact(v) {
  const n = Number(v);
  const units = [
    [1e9, "B"],
    [1e6, "M"],
    [1e3, "K"],
  ];
  for (const [size, suffix] of units) {
    if (Math.abs(n) >= size) return "$" + (n / size).toFixed(1) + suffix;
  }
  return "$" + n.toFixed(0);
}

// Rows for the "roster" list.
export function toRosterRows(items) {
  return items.map((item) => ({
    id: item.id,
    project: asText(item.project),
  }));
}

// "projectCount" = count. Design showed "3".
export function projectCount(items) {
  return asText(items.length);
}

// "plannedTotal" = sum(budget), shown as moneyCompact. Design showed "$245.0K".
export function plannedTotal(items) {
  return moneyCompact(items.reduce((s, x) => s + Number(x.budget), 0));
}

// "forecastTotal" = sum(forecast), shown as moneyCompact. Design showed "$245.0K".
export function forecastTotal(items) {
  return moneyCompact(items.reduce((s, x) => s + Number(x.forecast), 0));
}

export function findRoster(items, id) {
  return items.find((item) => item.id === id) ?? null;
}

// Form text -> the types the API expects (taken from the example request body).
export function toRosterInput(values) {
  return {
    project: String(values.project ?? "").trim(),
    lead: String(values.lead ?? "").trim(),
    deputy: String(values.deputy ?? "").trim(),
  };
}

// Raw values to prefill the form when an item is selected.
export function toFormValues(item) {
  if (!item) return {};
  return {
    project: item.project,
    lead: item.lead,
    deputy: item.deputy,
  };
}
