// Controller layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Connects the workflow and domain to the page. No business logic here.
import { useMachine } from "@xstate/react";
import { portfolioRedesignedWorkflow } from "../workflow/portfolio-redesigned.workflow.js";
import * as domain from "../domain/portfolio-redesigned.domain.js";
import PortfolioRedesignedPage from "../page/PortfolioRedesignedPage.jsx";

// PLACEHOLDER: "baselineSpend" is provided by the controller. The design showed "$280M".
function getBaselineSpend() {
  return "$280M";
}

// PLACEHOLDER: "row.spendChange" is provided by the controller for each row. The design showed "+$5.1M", "-$3.2M", "+$1.2M", "$0.0", "+$5.1M", "-$5.1M".
function getSpendChange(row) {
  return "+$5.1M";
}

// PLACEHOLDER: "suggest" page action — decide what it should do.
function handleSuggest() {
  console.warn("handleSuggest is a placeholder");
}

// PLACEHOLDER: "suggest" page action — decide what it should do.
function handleSuggest2() {
  console.warn("handleSuggest2 is a placeholder");
}

export default function PortfolioRedesignedController() {
  const [state, send] = useMachine(portfolioRedesignedWorkflow);
  const { data, items, selectedId, error } = state.context;

  return (
    <PortfolioRedesignedPage
      status={String(state.value)}
      error={error}
      refreshedAt={domain.refreshedAt(data)}
      headline={domain.headline(data)}
      improving={domain.improving(items)}
      declining={domain.declining(items)}
      baselineSpend={getBaselineSpend()}
      highCategories={domain.highCategories(items)}
      savingsRange={domain.savingsRange(items)}
      qualifiedCount={domain.qualifiedCount(items)}
      coveredCount={domain.coveredCount(data)}
      resilienceTotal={domain.resilienceTotal(data)}
      savingsCount={domain.savingsCount(data)}
      oldestDays={domain.oldestDays(items)}
      qualifiedInitiatives={domain.qualifiedInitiatives(items)}
      rows={domain
        .toPortfolioRedesignedRows(items)
        .map((row) => ({ ...row, spendChange: getSpendChange(row) }))}
      selectedId={selectedId}
      onOpen={(id) => send({ type: "OPEN", id })}
      onSuggest={handleSuggest}
      onSuggest={handleSuggest2}
    />
  );
}
