// Page layer — generated by line-matcher from the design. Props in, JSX out; no business logic.
import ProductRow from "../component/ProductRow.jsx";

export default function ProductsPage({
  status,
  error,
  productCount,
  stockTotal,
  avgPrice,
  rows,
  selectedId,
  formValues,
  onEdit,
  onDelete,
  onSave,
  onCancel,
}) {
  return (
    <main className="page">
      {status === "loading" && <p className="status">Loading…</p>}
      {error && (
        <p role="alert" className="error">
          {error}
        </p>
      )}
      <header className="header">
        <h1>Products</h1>
        <p className="meta">
          <span>{productCount}</span>
          {" products · stock "}
          <span>{stockTotal}</span>
          {" units · average price "}
          <span>{avgPrice}</span>
        </p>
      </header>

      <form
        className="card form"
        key={selectedId ?? "new"}
        onSubmit={(e) => {
          e.preventDefault();
          onSave(Object.fromEntries(new FormData(e.currentTarget)));
        }}
      >
        <input name="name" placeholder="Name" required defaultValue={formValues.name ?? ""} />
        <input
          name="price"
          type="number"
          placeholder="Price"
          required
          defaultValue={formValues.price ?? ""}
        />
        <input
          name="stock"
          type="number"
          placeholder="Stock"
          required
          defaultValue={formValues.stock ?? ""}
        />
        <button type="submit" className="primary">
          Save
        </button>
        <button type="button" onClick={onCancel}>
          Cancel
        </button>
      </form>

      <table className="card table">
        <thead>
          <tr>
            <th>Product</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Added</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <ProductRow
              key={row.id}
              row={row}
              selected={row.id === selectedId}
              onEdit={onEdit}
              onDelete={onDelete}
            />
          ))}
        </tbody>
      </table>
    </main>
  );
}
