// Route layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Navigation entry point. Delegates to the controller.
import MetricsController from "../controller/MetricsController.jsx";

export const path = "/metrics";

export default function MetricsRoute() {
  return <MetricsController />;
}
