// @construct-generated tests v1 - LOCKED, do not edit (#348)
// Generated by `construct generate tests`. Regenerated whenever the workflow changes; edits are refused.
// To change it: clone it to features/refunds/tests/ (one level up), where nothing regenerates it.
// feature: "refunds"
// machine: "refundRequest" ("workflows/RefundRequest.ts"), key "refund-request"
// scenario: "happy-path" - "Happy path"
// route: submitted → auto check → approved → refunded → closed
// machine-hash: sha256:efda545fc46e0c23437ad7a48e8b2a06da49a2b416682216cfd84d1ae983dc17
// scenario-hash: sha256:f36e8ec0f0d4f03f4697c86b99165993b7bb9324260edfd2430b22e5534cc10d

// Given the flow starts in *submitted*
// When "request refund" happens
// Then the flow moves to *auto check*
// And when it is low value
// Then the flow moves to *approved*
// And when `issueRefund` finishes successfully
// Then the flow moves to *refunded*
// And when "close" happens
// Then the flow moves to *closed*
// And the flow ends — *closed* is an end state
// Note: in *approved* the flow can start that step over when `issueRefund` fails, so this part can repeat.

import { test, expect, type Page } from '@playwright/test';

// TODO(construct): no route reaches this feature
const START_URL: string | null = null;
const MACHINE = "refund-request";

const harness = (selector: string, why: string) =>
  new Error(
    `Test harness problem, not a bug in the page: the test harness expected ${selector}. ` +
      `${why} Construct binds workflow events to elements by convention (data-testid = the event name in kebab-case; ` +
      `data-flow / data-flow-state on the element that shows the machine's state). ` +
      `Add the attribute (or scaffold the page with \`construct create page --from\`); do not file a product bug for this.`,
  );

async function required(page: Page, selector: string, why: string) {
  const el = page.locator(selector).first();
  try {
    await el.waitFor({ state: 'attached', timeout: 5_000 });
  } catch {
    throw harness(selector, why);
  }
  return el;
}

async function trigger(page: Page, testId: string, event: string) {
  const el = await required(page, `[data-testid="${testId}"]`, `It is what the workflow event ${event} binds to.`);
  await el.click();
}

async function expectFlowState(page: Page, machine: string, state: string, timeout = 5_000) {
  const el = await required(page, `[data-flow="${machine}"][data-flow-state]`, `It shows the state of the ${machine} workflow.`);
  await expect(el).toHaveAttribute('data-flow-state', state, { timeout });
}

test("refunds / refundRequest / Happy path", async ({ page }) => {
  test.fixme(true, "TODO(construct): no route reaches this feature - set START_URL in a clone of this file");
  test.fixme(true, "needs a fixture where the guard \"isLowValue\" holds");
  if (START_URL === null) return;
  await page.goto(START_URL);
  await expectFlowState(page, MACHINE, "submitted");
  // When "request refund" happens
  await trigger(page, "request-refund", "REQUEST_REFUND");
  await expectFlowState(page, MACHINE, "approved");
  // Then its service finishes
  await expectFlowState(page, MACHINE, "refunded");
  // When "close" happens
  await trigger(page, "close", "CLOSE");
  await expectFlowState(page, MACHINE, "closed");
});
