// Component layer — generated by line-matcher. Reusable presentation only.
export default function InvoiceRow({ row, selected, onEdit, onArchive, onDelete }) {
  return (
    <tr data-selected={selected ? "true" : undefined}>
      <td>{row.number}</td>
      <td>{row.vendor}</td>
      <td className="num">{row.amount}</td>
      <td>{row.dueDate}</td>
      <td>{row.requestedBy}</td>
      <td>{row.status}</td>
      <td className="actions">
        <button onClick={() => onEdit(row.id)}>Edit</button>
        <button onClick={() => onArchive(row.id)}>Archive</button>
        <button className="danger" onClick={() => onDelete(row.id)}>
          Delete
        </button>
      </td>
    </tr>
  );
}
