// Controller layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Connects the workflow and domain to the page. No business logic here.
import { useMachine } from "@xstate/react";
import { invoicesWorkflow } from "../workflow/invoices.workflow.js";
import * as domain from "../domain/invoices.domain.js";
import InvoicesPage from "../page/InvoicesPage.jsx";

// PLACEHOLDER: "largestInvoice" is provided by the controller. The design showed "$48.2M".
function getLargestInvoice() {
  return "$48.2M";
}

// PLACEHOLDER: "syncedAt" is provided by the controller. The design showed "26 Sep 2026".
function getSyncedAt() {
  return "26 Sep 2026";
}

// PLACEHOLDER: "row.requestedBy" is provided by the controller for each row. The design showed "Lena", "Mia", "Prerna", "Arjun".
function getRequestedBy(row) {
  return "Lena";
}

// PLACEHOLDER: "row.status" is provided by the controller for each row. The design showed "Overdue", "Overdue", "Open", "Partial".
function getStatus(row) {
  return "Overdue";
}

// PLACEHOLDER: "archive" row action — decide what it should do.
function handleArchive(id) {
  console.warn("handleArchive is a placeholder", id);
}

export default function InvoicesController() {
  const [state, send] = useMachine(invoicesWorkflow);
  const { items, selectedId, error } = state.context;

  return (
    <InvoicesPage
      status={String(state.value)}
      error={error}
      invoiceCount={domain.invoiceCount(items)}
      totalBilled={domain.totalBilled(items)}
      largestInvoice={getLargestInvoice()}
      syncedAt={getSyncedAt()}
      rows={domain
        .toInvoiceRows(items)
        .map((row) => ({ ...row, requestedBy: getRequestedBy(row), status: getStatus(row) }))}
      selectedId={selectedId}
      formValues={domain.toFormValues(domain.findInvoice(items, selectedId))}
      onEdit={(id) => send({ type: "EDIT", id })}
      onArchive={handleArchive}
      onDelete={(id) => send({ type: "DELETE", id })}
      onSave={(values) => send({ type: "SAVE", data: domain.toInvoiceInput(values) })}
      onCancel={() => send({ type: "CANCEL" })}
    />
  );
}
