// Domain layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Pure functions only: no network, storage or DOM.

export function asText(v) {
  return String(v);
}

export function moneyCompact(v) {
  const n = Number(v);
  const units = [
    [1e9, "B"],
    [1e6, "M"],
    [1e3, "K"],
  ];
  for (const [size, suffix] of units) {
    if (Math.abs(n) >= size) return "$" + (n / size).toFixed(1) + suffix;
  }
  return "$" + n.toFixed(0);
}

// Rows for the "categories" list, sort by spend descending.
export function toCategoryRows(items) {
  return [...items]
    .sort((a, b) => {
      const x = a.spend,
        y = b.spend;
      const c =
        typeof x === "number" && typeof y === "number" ? x - y : String(x).localeCompare(String(y));
      return -c;
    })
    .map((item) => ({
      id: item.id,
      name: asText(item.name),
      spend: moneyCompact(item.spend),
      owner: asText(item.owner),
    }));
}

// "categoryCount" = count. Design showed "4".
export function categoryCount(items) {
  return asText(items.length);
}

// "totalSpend" = sum(spend), shown as moneyCompact. Design showed "$278.0M".
export function totalSpend(items) {
  return moneyCompact(items.reduce((s, x) => s + Number(x.spend), 0));
}

// "largestSpend" = max(spend), shown as moneyCompact. Design showed "$91.6M".
export function largestSpend(items) {
  return moneyCompact(items.length ? Math.max(...items.map((x) => Number(x.spend))) : 0);
}

// TODO: "refreshedAt" (design showed "31 Jul 2026") is not in the API yet.
export function refreshedAt() {
  return "—";
}

export function findCategory(items, id) {
  return items.find((item) => item.id === id) ?? null;
}

// Form text -> the types the API expects (taken from the example request body).
export function toCategoryInput(values) {
  return {
    name: String(values.name ?? "").trim(),
    spend: Number(values.spend),
    owner: String(values.owner ?? "").trim(),
  };
}

// Raw values to prefill the form when an item is selected.
export function toFormValues(item) {
  if (!item) return {};
  return {
    name: item.name,
    spend: item.spend,
    owner: item.owner,
  };
}
