// Controller layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Connects the workflow and domain to the page. No business logic here.
import { useMachine } from "@xstate/react";
import { categoriesWorkflow } from "../workflow/categories.workflow.js";
import * as domain from "../domain/categories.domain.js";
import CategoriesPage from "../page/CategoriesPage.jsx";

export default function CategoriesController() {
  const [state, send] = useMachine(categoriesWorkflow);
  const { items, selectedId, error } = state.context;

  return (
    <CategoriesPage
      status={String(state.value)}
      error={error}
      categoryCount={domain.categoryCount(items)}
      totalSpend={domain.totalSpend(items)}
      largestSpend={domain.largestSpend(items)}
      refreshedAt={domain.refreshedAt(items)}
      rows={domain.toCategoryRows(items)}
      selectedId={selectedId}
      formValues={domain.toFormValues(domain.findCategory(items, selectedId))}
      onEdit={(id) => send({ type: "EDIT", id })}
      onDelete={(id) => send({ type: "DELETE", id })}
      onSave={(values) => send({ type: "SAVE", data: domain.toCategoryInput(values) })}
      onCancel={() => send({ type: "CANCEL" })}
    />
  );
}
