// Route layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Navigation entry point. Delegates to the controller.
import InvoicesController from "../controller/InvoicesController.jsx";

export const path = "/invoices";

export default function InvoicesRoute() {
  return <InvoicesController />;
}
