// Domain layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Pure functions only: no network, storage or DOM.

// Reads a dotted path ("a.b.c") from the response.
const get = (o, path) => path.split(".").reduce((x, k) => x?.[k], o);

export function asText(v) {
  return String(v);
}

export function moneyCompact(v) {
  const n = Number(v);
  const units = [
    [1e9, "B"],
    [1e6, "M"],
    [1e3, "K"],
  ];
  for (const [size, suffix] of units) {
    if (Math.abs(n) >= size) return "$" + (n / size).toFixed(1) + suffix;
  }
  return "$" + n.toFixed(0);
}

export function percentWhole(v) {
  return Math.round(Number(v) * 100) + "%";
}

export function percent(v) {
  return (Number(v) * 100).toFixed(1) + "%";
}

export function dateShort(v) {
  const d = new Date(v);
  const m = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return d.getUTCDate() + " " + m[d.getUTCMonth()] + " " + d.getUTCFullYear();
}

// Rows for the "portfolio-figma-1" list.
export function toPortfolioFigma1Rows(items) {
  return items.map((item) => ({
    id: item.beroe_l2_id,
    name: asText(item.display_name),
    share: percent(item.spend.pct_of_total),
    savings: moneyCompact(item.savings_potential),
  }));
}

// TODO: "categoryCount" (design showed "6") was skipped in Q&A — decide where it comes from.
export function categoryCount() {
  return "—";
}

// "spendYouManage" = the response field "portfolio_at_a_glance.spend_you_manage", shown as moneyCompact. Design showed "$280.2M".
export function spendYouManage(data) {
  return moneyCompact(get(data, "portfolio_at_a_glance.spend_you_manage"));
}

// "refreshedAt" = the response field "meta.snapshot_date", shown as dateShort. Design showed "31 Jul 2026".
export function refreshedAt(data) {
  return dateShort(get(data, "meta.snapshot_date"));
}

// "headline" = the response field "narrative.cross_l2_summary". Design showed "Grains is carrying your portfolio. Logistics and Packaging are not.".
export function headline(data) {
  return asText(get(data, "narrative.cross_l2_summary"));
}

// TODO: "improving" (design showed "Grains, up on contract coverage and a renegotiated origination mix, and Chemicals, where the solvent index fell two quarters running.") was skipped in Q&A — decide where it comes from.
export function improving() {
  return "—";
}

// TODO: "declining" (design showed "Logistics, where the maturity gap widened to -0.7 and three high flags are open, and Packaging, where supplier concentration moved the wrong way. IT & Software is flat.") was skipped in Q&A — decide where it comes from.
export function declining() {
  return "—";
}

// TODO: "spendCard" (design showed "$280M") was skipped in Q&A — decide where it comes from.
export function spendCard() {
  return "—";
}

// TODO: "spendYoy" (design showed "▲ 8.4% YoY") was skipped in Q&A — decide where it comes from.
export function spendYoy() {
  return "—";
}

// "largestName" = the response field "portfolio_at_a_glance.largest_category.display_name". Design showed "Grains & Cereals".
export function largestName(data) {
  return asText(get(data, "portfolio_at_a_glance.largest_category.display_name"));
}

// "largestShare" = the response field "portfolio_at_a_glance.largest_category.share_of_portfolio", shown as percentWhole. Design showed "33%".
export function largestShare(data) {
  return percentWhole(get(data, "portfolio_at_a_glance.largest_category.share_of_portfolio"));
}

// "savingsCard" = the response field "portfolio_at_a_glance.savings_potential.value", shown as moneyCompact. Design showed "$24.5M".
export function savingsCard(data) {
  return moneyCompact(get(data, "portfolio_at_a_glance.savings_potential.value"));
}

// "acceptedPct" = the response field "portfolio_at_a_glance.savings_potential.qualified_accepted_pct", shown as percentWhole. Design showed "38%".
export function acceptedPct(data) {
  return percentWhole(get(data, "portfolio_at_a_glance.savings_potential.qualified_accepted_pct"));
}

// TODO: "acceptedCount" (design showed "23 of 60") was skipped in Q&A — decide where it comes from.
export function acceptedCount() {
  return "—";
}

// "resilienceTotal" = the response field "portfolio_at_a_glance.resilience_initiatives.total". Design showed "21".
export function resilienceTotal(data) {
  return asText(get(data, "portfolio_at_a_glance.resilience_initiatives.total"));
}

// "impactHigh" = the response field "portfolio_at_a_glance.resilience_initiatives.by_impact.high". Design showed "7".
export function impactHigh(data) {
  return asText(get(data, "portfolio_at_a_glance.resilience_initiatives.by_impact.high"));
}

// "impactMedium" = the response field "portfolio_at_a_glance.resilience_initiatives.by_impact.medium". Design showed "13".
export function impactMedium(data) {
  return asText(get(data, "portfolio_at_a_glance.resilience_initiatives.by_impact.medium"));
}

// "impactLow" = the response field "portfolio_at_a_glance.resilience_initiatives.by_impact.low". Design showed "1".
export function impactLow(data) {
  return asText(get(data, "portfolio_at_a_glance.resilience_initiatives.by_impact.low"));
}

// TODO: "highCategories" (design showed "4") was skipped in Q&A — decide where it comes from.
export function highCategories() {
  return "—";
}

// "savingsCount" = the response field "portfolio_at_a_glance.waiting_on_decision.savings_count". Design showed "26".
export function savingsCount(data) {
  return asText(get(data, "portfolio_at_a_glance.waiting_on_decision.savings_count"));
}

// TODO: "savingsTarget" (design showed "$42.0M") was skipped in Q&A — decide where it comes from.
export function savingsTarget() {
  return "—";
}

// TODO: "oldestDays" (design showed "34") was skipped in Q&A — decide where it comes from.
export function oldestDays() {
  return "—";
}

// TODO: "riskCount" (design showed "6") was skipped in Q&A — decide where it comes from.
export function riskCount() {
  return "—";
}

// TODO: "riskCategories" (design showed "2") was skipped in Q&A — decide where it comes from.
export function riskCategories() {
  return "—";
}

// TODO: "riskTarget" (design showed "8.0") was skipped in Q&A — decide where it comes from.
export function riskTarget() {
  return "—";
}

export function findPortfolioFigma1(items, id) {
  return items.find((item) => item.beroe_l2_id === id) ?? null;
}
