// Controller layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Connects the workflow and domain to the page. No business logic here.
import { useMachine } from "@xstate/react";
import { ordersWorkflow } from "../workflow/orders.workflow.js";
import * as domain from "../domain/orders.domain.js";
import OrdersPage from "../page/OrdersPage.jsx";

// PLACEHOLDER: "row.status" is provided by the controller for each row. The design showed "Shipped", "Pending", "Shipped".
function getStatus(row) {
  return "Shipped";
}

// PLACEHOLDER: "delete" row action — decide what it should do.
function handleDelete(id) {
  console.warn("handleDelete is a placeholder", id);
}

export default function OrdersController() {
  const [state, send] = useMachine(ordersWorkflow);
  const { items, selectedId, error } = state.context;

  return (
    <OrdersPage
      status={String(state.value)}
      error={error}
      orderCount={domain.orderCount(items)}
      totalValue={domain.totalValue(items)}
      rows={domain.toOrderRows(items).map((row) => ({ ...row, status: getStatus(row) }))}
      selectedId={selectedId}
      formValues={domain.toFormValues(domain.findOrder(items, selectedId))}
      onEdit={(id) => send({ type: "EDIT", id })}
      onDelete={handleDelete}
      onCancel={() => send({ type: "CANCEL" })}
    />
  );
}
