// Component layer — generated by line-matcher. Reusable presentation only.
export default function PortfolioRedesignedRow({ row, selected, onOpen }) {
  return (
    <tr data-selected={selected ? "true" : undefined}>
      <td>
        <span>01</span>
      </td>
      <td>
        <span>{row.name}</span> <span className="badge">L2</span>{" "}
        <span className="badge">37% of total spend</span>{" "}
        <span className="badge">5 qualified opportunities</span>{" "}
        <span className="badge">5 accepted</span>
      </td>
      <td className="num">
        <span>$78.4M</span>
      </td>
      <td>
        <span>2.0</span> <span>peer 2.7</span>
      </td>
      <td className="num">
        <span>$4.7M - $5.6M</span>
      </td>
      <td className="num">
        <span>{row.risk}</span>
      </td>
      <td className="num">
        <span>{row.spendChange}</span>
      </td>
      <td className="actions">
        <button onClick={() => onOpen(row.id)}>Open</button>
      </td>
    </tr>
  );
}
