// #629, #630, #625 (part of epic #616) -- what the proofs of the guard, store and handler blocks share. Each of the three blocks writes its own locked
// proof next to its units (`features/<f>/tests/generated/<Name>Guard.proof.test.ts`, `<Name>Store.proof.test.ts`, `<Name>Api.proof.test.ts`), so the block is
// shown to work the way a shaped screen is (proof.mjs): the same marker, the same test regions in architecture.yml, the same runner
// (`construct test proof <feature>`), the same failure words (`Expected: "..."` and `Received: "..."` lines name the state that is wrong).
//
//   proofHeader(request)                     the marker and the three comment lines every proof starts with
//   EXPECT_LINES                             the helper a proof fails through: it names WHAT was wrong and the state it reached
//   blockProofTouches(root, feature, file)   the proof and architecture.yml, as a step's `touches.files`
//   writeBlockProof(root, feature, file, text) write it (locked, idempotent); returns whether the bytes changed
import fs from 'node:fs';
import path from 'node:path';
import { ConstructError, EXIT_CODES } from './diagnostics.mjs';
import { ensureTestRegions, generatedDir } from './proof.mjs';
import { GENERATED_MARKER, assertSafeDir } from '../engine/testGenerator.mjs';
import { comment, lit } from '../engine/testSpecRender.mjs';

const usage = (message) => new ConstructError(message, { exitCode: EXIT_CODES.USAGE_ERROR });
const rel = (root, abs) => path.relative(root, abs).split(path.sep).join('/');

/**
 * The lines every block proof starts with: the generated-test marker (it makes the file locked), the command that regenerates it and what it proves.
 *
 * @param {{ command: string, feature: string, subject: string }} request The regenerating command, the feature and what the proof is about (`Products guard`).
 * @returns {string[]} The header lines.
 *
 * @example
 * proofHeader({ command: 'construct create guard Products --feature shop --access signed-in', feature: 'shop', subject: 'Products guard' })[0]; // => '// @construct-generated tests v1 - LOCKED, do not edit (#348)'
 */
export function proofHeader({ command, feature, subject }) {
  return [
    GENERATED_MARKER,
    `// Generated by \`${comment(command)}\`. Regenerated by the same command; edits are refused (it is a proof: the block changes, the proof does not).`,
    `// feature: ${lit(feature)}`,
    `// proof: ${lit(subject)}`,
  ];
}

/** The helper every block proof fails through: the message says what was wrong, and its `Expected` and `Received` lines name the states, which is what the runner classifies as "the app behaved differently". */
export const EXPECT_LINES = Object.freeze([
  '/** Fails with the state that is wrong, in the words the test runner classifies: the Expected and Received lines name states. */',
  'function expectState(what: string, want: string, got: string): void {',
  '  if (got === want) return;',
  "  const message = what + ': the ' + want + ' state is wrong, it reaches ' + got + '.\\nExpected: \"' + want + '\"\\nReceived: \"' + got + '\"';",
  "  throw new assert.AssertionError({ message, actual: got, expected: want, operator: 'strictEqual' });",
  '}',
]);

/**
 * The files a block proof step declares: the proof (`create`) and `architecture.yml` (`modify`: the generated-test regions, once).
 *
 * @param {string} root Project root.
 * @param {string} feature The feature the proof belongs to.
 * @param {string} fileName The proof's file name (`ProductsGuard.proof.test.ts`).
 * @returns {{ path: string, change: 'create'|'modify' }[]} The declared files.
 * @throws {Error} A usage error for an invalid feature name.
 *
 * @example
 * blockProofTouches(root, 'shop', 'ProductsGuard.proof.test.ts').map((f) => f.path); // => ['features/shop/tests/generated/ProductsGuard.proof.test.ts', 'architecture.yml']
 */
export function blockProofTouches(root, feature, fileName) {
  const { genRel } = generatedDir(root, feature);
  return [{ path: `${genRel}/${fileName}`, change: 'create' }, { path: 'architecture.yml', change: 'modify' }];
}

/**
 * Write a block proof: refuses to overwrite a file that is not a marker-bearing generated proof, declares the generated-test regions in
 * architecture.yml once (`frozen:` locks it, `nonLayer:` keeps it out of the layer graph) and leaves the file alone when its bytes are already right.
 *
 * @param {string} root Project root.
 * @param {string} feature The feature (it must exist).
 * @param {string} fileName The proof's file name.
 * @param {string} content The proof's text.
 * @returns {{ file: string, changed: boolean, regions: string[] }} The project-relative file, whether it was written, and the architecture.yml keys added.
 * @throws {Error} A usage error for a missing feature, a file that is not a generated proof, or half-declared test regions.
 *
 * @example
 * writeBlockProof(root, 'shop', 'ProductsGuard.proof.test.ts', text); // => { file: 'features/shop/tests/generated/ProductsGuard.proof.test.ts', changed: true, regions: ['frozen', 'nonLayer'] }
 */
export function writeBlockProof(root, feature, fileName, content) {
  const { genRel, genDir, featureDir } = generatedDir(root, feature);
  if (!fs.existsSync(featureDir) || !fs.statSync(featureDir).isDirectory()) throw usage(`Feature "${feature}" not found (looked in ${rel(root, featureDir)}). Create it first: construct create feature ${feature}`);
  assertSafeDir(root, genRel);
  const file = path.join(genDir, fileName);
  let existing = null;
  try {
    const st = fs.lstatSync(file);
    if (st.isSymbolicLink() || !st.isFile()) throw usage(`Refusing to overwrite ${rel(root, file)}: it is not a regular file.`);
    existing = fs.readFileSync(file, 'utf8');
    if (!existing.startsWith(`${GENERATED_MARKER}\n`)) throw usage(`Refusing to overwrite ${rel(root, file)}: it is not a generated proof (no ${JSON.stringify(GENERATED_MARKER)} marker).`);
  } catch (e) {
    if (e instanceof ConstructError) throw e;
  }
  const regions = ensureTestRegions(root, genDir);
  if (existing === content) return { file: rel(root, file), changed: false, regions };
  fs.mkdirSync(genDir, { recursive: true });
  assertSafeDir(root, genRel);
  fs.writeFileSync(file, content);
  return { file: rel(root, file), changed: true, regions };
}
