// #437 (part of #433, serves #395's rules composer) -- export architecture.yml's layer graph
// to a target project's own CI tooling. Construct stays the source of truth (`loadConfig()`'s
// `layers`/`rules`/`frozen`/`nonLayer`); this module only renders an equivalent config for a
// tool the target project already runs. dependency-cruiser/eslint-plugin-boundaries stay the
// TARGET project's devDependency -- never added here (see package.json).
//
// Two targets:
//  - dependency-cruiser: "forbidden" rules only (a denylist of path-regex pairs). Six of them
//    mirror the AST-based import-path checks architecture-enforcer.mjs already runs under the
//    names PAGE-002/003/005, COMPONENT-002/003, WORKFLOW-001, SERVICE-002 (BOUNDARY_RULE_SPECS
//    below) -- same names, same severity gate (an `architecture.yml` rules: override that turns
//    one of those codes 'off' removes the matching generated rule), same layer grouping the
//    report (docs/EXPLORATION-2026-09-oss-plugins.md #8) called out. Every OTHER declared layer
//    (custom layers, and the canonical route/hook/domain/expression layers that predate those
//    six codes and were never covered by them) gets a second, fully general rule instead: every
//    edge NOT in that layer's own `canImport` is forbidden. This is deliberately a superset of
//    the old static 6-line `.dependency-cruiser.cjs` (itself only 3 lines / 3 rules by the time
//    of #437, already stale against the current 9-layer default graph) -- see this module's own
//    tests and the #437 issue comment for the byte-for-byte tradeoff this makes.
//  - eslint-boundaries (eslint-plugin-boundaries, flat config): #513 (closed, a spike that
//    predates this issue's own dependency-cruiser work landing) already built and tested a
//    complete generator for this target -- exportArchitectureRules.mjs's
//    `generateEslintFlatConfigModule(root)` -- reused here as-is (`renderCiExport` below) rather
//    than duplicated. It is a direct, complete translation (one `elements` entry per layer, one
//    `boundaries/dependencies` policy per layer's own `canImport`): unlike dependency-cruiser's
//    forbidden-only model, eslint-plugin-boundaries natively models "allowed edges", so it needs
//    no curated/generic split.
//
// Both targets are lossy: neither can express a semantic/AST check (state hooks, fetch calls,
// purity, naming conventions, JSX complexity...) as a path rule. `notExpressibleRules()` lists
// every OTHER enabled rule in `architecture.yml` so the export output can say so explicitly.
import crypto from 'node:crypto';
import { globToRegExp } from './glob.mjs';
import { generateEslintFlatConfigModule } from './exportArchitectureRules.mjs';

const GENERATED_HEADER = 'generated by Construct (construct sync / construct export ci) -- do not edit by hand; edit architecture.yml instead';

/** The six named layer-boundary checks architecture-enforcer.mjs already runs as AST/import-path
 * checks (see the module doc comment above). `codes` gates the rule on `config.rules[code]`
 * severity (any code active -- not 'off' -- keeps the rule; every code 'off' drops it). */
const BOUNDARY_RULE_SPECS = [
  { name: 'page-to-workflow', from: 'page', to: ['workflow'], codes: ['PAGE-002'] },
  { name: 'page-to-service', from: 'page', to: ['service'], codes: ['PAGE-003'] },
  { name: 'page-to-domain', from: 'page', to: ['domain'], codes: ['PAGE-005'] },
  { name: 'component-to-app-logic', from: 'component', to: ['controller', 'workflow', 'service', 'domain'], codes: ['COMPONENT-002', 'COMPONENT-003'] },
  { name: 'workflow-to-ui', from: 'workflow', to: ['page', 'component'], codes: ['WORKFLOW-001'] },
  { name: 'service-to-ui', from: 'service', to: ['page', 'component'], codes: ['SERVICE-002'] },
];

const isRuleActive = (rules, codes) => codes.some((code) => (rules?.[code]?.severity ?? 'off') !== 'off');

/** Layers that declare a `pattern` (pseudo-layers like `types` never do, and are never a
 * dependency-cruiser/eslint-boundaries "from" or "to" -- there is no file to classify as one). */
const patternedLayers = (layers) => Object.entries(layers).filter(([, def]) => def && def.pattern);

/**
 * Derive the forbidden-edge rule set for `export ci --target dependency-cruiser` (and `sync`'s
 * default `.dependency-cruiser.cjs`) from a loaded `architecture.yml` (`loadConfig()`'s return).
 *
 * @param {ReturnType<import('./config.mjs').loadConfig>} config
 * @returns {{ name: string, fromPattern: string, toPatterns: string[] }[]} One entry per forbidden rule, already gated by rule severity and layer presence.
 */
export function dependencyCruiserBoundaryRules(config) {
  const layers = config.layers || {};
  const patterned = new Map(patternedLayers(layers));
  const rules = config.rules || {};
  const out = [];
  const curatedFromLayers = new Set();

  for (const spec of BOUNDARY_RULE_SPECS) {
    if (!patterned.has(spec.from)) continue;
    const to = spec.to.filter((t) => patterned.has(t));
    if (!to.length) continue;
    if (!isRuleActive(rules, spec.codes)) continue;
    curatedFromLayers.add(spec.from);
    out.push({ name: spec.name, fromPattern: patterned.get(spec.from).pattern, toPatterns: to.map((t) => patterned.get(t).pattern) });
  }

  // Every layer the curated specs above don't already cover as a `from` (custom layers, plus
  // route/hook/domain/expression, which predate BOUNDARY_RULE_SPECS): forbid every edge not in
  // its own `canImport`, so no declared layer is silently unenforced in the exported config.
  for (const [name, def] of patterned) {
    if (curatedFromLayers.has(name)) continue;
    const canImport = new Set(def.canImport || []);
    const disallowed = [...patterned.keys()].filter((t) => t !== name && !canImport.has(t));
    if (!disallowed.length) continue;
    out.push({ name: `${name}-boundary`, fromPattern: def.pattern, toPatterns: disallowed.map((t) => patterned.get(t).pattern) });
  }

  return out;
}

/** Rule codes from `architecture.yml`'s `rules:` map that no path-regex export can express
 * (AST/semantic checks: state hooks, fetch calls, purity, naming, JSX complexity, workflow
 * reachability, numeric overrides...). Everything in `config.rules` that is enabled (severity
 * not 'off') and not one of BOUNDARY_RULE_SPECS' own codes lands here.
 * @param {ReturnType<import('./config.mjs').loadConfig>} config
 * @returns {string[]} the not-expressible rule codes, sorted.
 */
export function notExpressibleRules(config) {
  const boundaryCodes = new Set(BOUNDARY_RULE_SPECS.flatMap((s) => s.codes));
  return Object.entries(config.rules || {})
    .filter(([code, def]) => !boundaryCodes.has(code) && !def?.numeric && (def?.severity ?? 'off') !== 'off')
    .map(([code]) => code)
    .sort();
}

const regexSourceOf = (glob) => globToRegExp(glob).source;
const excludeRegexSource = (config) => {
  const globs = [...(config.frozen || []), ...(config.nonLayer || [])];
  return globs.length ? globs.map(regexSourceOf).join('|') : null;
};

const hashOf = (value) => crypto.createHash('sha256').update(value).digest('hex').slice(0, 16);

/**
 * Render `.dependency-cruiser.cjs` content for `config` (a `loadConfig()` result): a
 * "generated by Construct" header, a content hash for drift detection, and one `forbidden`
 * rule per `dependencyCruiserBoundaryRules(config)` entry, plus `options.exclude` for any
 * `frozen:`/`nonLayer:` region (#437 acceptance: "frozen/nonLayer regions handled").
 *
 * @param {ReturnType<import('./config.mjs').loadConfig>} config
 * @returns {string} A complete `.dependency-cruiser.cjs` file (CommonJS, `module.exports = {...}`).
 */
export function renderDependencyCruiserConfig(config) {
  const boundaryRules = dependencyCruiserBoundaryRules(config);
  const forbidden = boundaryRules.map((r) => ({
    name: r.name,
    severity: 'error',
    from: { path: regexSourceOf(r.fromPattern) },
    to: { path: r.toPatterns.length === 1 ? regexSourceOf(r.toPatterns[0]) : r.toPatterns.map(regexSourceOf).join('|') },
  }));
  const exclude = excludeRegexSource(config);
  const body = { forbidden, ...(exclude ? { options: { exclude: { path: exclude } } } : {}) };
  const hash = hashOf(JSON.stringify(body));
  const notExpressible = notExpressibleRules(config);
  return [
    `// ${GENERATED_HEADER}`,
    `// hash: ${hash}`,
    notExpressible.length
      ? `// Not expressible as a path rule (semantic/AST checks -- still enforced by \`construct validate\`): ${notExpressible.join(', ')}`
      : '// Every enabled architecture.yml rule is expressible as a path rule.',
    `module.exports = ${JSON.stringify(body, null, 2)};`,
    '',
  ].join('\n');
}

export const EXPORT_CI_TARGETS = ['dependency-cruiser', 'eslint-boundaries'];

/** `construct export ci --target <target>` entry point: `target` is `'dependency-cruiser'` or
 * `'eslint-boundaries'`. Throws (caller's job to turn into a usage error) on an unknown target.
 * `root` is only used by the eslint-boundaries target (exportArchitectureRules.mjs's generator
 * re-reads architecture.yml itself via `loadLayerGraph(root)`, #513).
 * @param {string} root - project root.
 * @param {ReturnType<import('./config.mjs').loadConfig>} config
 * @param {string} target - one of `EXPORT_CI_TARGETS`.
 * @returns {string} the rendered CI config file content.
 */
export function renderCiExport(root, config, target) {
  if (target === 'dependency-cruiser') return renderDependencyCruiserConfig(config);
  if (target === 'eslint-boundaries') return generateEslintFlatConfigModule(root);
  throw new Error(`Unknown export ci target "${target}" -- expected one of ${EXPORT_CI_TARGETS.join(', ')}.`);
}
