// #620, #626 (part of epic #616) -- the render proofs of the `detail` and `form` shapes, as generated node tests (proof.mjs writes and locks
// them, `construct test proof` runs them). Each proof shows the screen the shape wrote BEHAVES, with no browser and no server: every state
// from sample props (react-dom/server), the controller's first state, the pure domain unit, and the service with a stubbed fetch. A failure
// names the state that is wrong (`the not-found state is wrong, the screen shows loading`), so a person, an LLM or the runner can act on it.
//
// proof.mjs owns the file, the header and the helpers every proof shares; it passes them in as `kit`, so this file needs nothing from it.
import { kebab, labelOf } from './shape-kit.mjs';
import { inputFieldsOf } from './shape-form.mjs';
import { proofViews, statesFlag } from './shape-states.mjs';

/**
 * @typedef {{ header: (extra: string, command: string) => string[], expectLines: string[], fetchLines: string[], lit: (value: string) => string, rowLiteral: (row: object) => string, comment: (text: string) => string }} ProofKit
 * What proof.mjs hands the proofs of the other shapes: the generated-file header, the shared helper text, and how to write a literal.
 */

/** How a field of the sample row reads on the details screen: a string as it is, a number by `String`, a boolean as Yes or No. */
/**
 * The ` --source <name>` of a proof's own command line: none for `endpoint` (what no source means), so a proof written before the source existed is regenerated byte for byte.
 *
 * @param {{ source: string }} ctx The shape context.
 * @returns {string} The flag with a leading space, or an empty string.
 *
 * @example
 * sourceFlag({ source: 'local' }); // => ' --source local'
 */
export const sourceFlag = (ctx) => (ctx.source === 'endpoint' ? '' : ` --source ${ctx.source}`);
/**
 * How a value of the sample row reads on the details screen: a string as it is, a number by `String`, a boolean as Yes or No.
 *
 * @param {{ type: string }} f The parsed field.
 * @param {string|number|boolean} value The value of the sample row.
 * @returns {string} The text on the screen.
 *
 * @example
 * shownValue({ type: 'boolean' }, true); // => 'Yes'
 */
export const shownValue = (f, value) => (f.type === 'boolean' ? (value ? 'Yes' : 'No') : String(value));

/**
 * The text of the render proof of a detail screen: loading, not found, ready (every field with its label and its value), error with
 * role alert, the controller's first state, the domain lines, and the service with a stubbed fetch (200, 404, 500, wrong shape, network
 * failure, the id in the address, the AbortSignal).
 *
 * @param {object} ctx The proof context (shape context plus `rows`, `loadingText`, `notFoundText`, `errorText`).
 * @param {{ feature: string }} request The proof request.
 * @param {string} relPath The project-relative path of the proof file, for its run line.
 * @param {ProofKit} kit The shared header and helpers.
 * @returns {string} The file text, ending with a newline.
 *
 * @example
 * detailProofText(ctx, { feature: 'products' }, 'features/products/tests/generated/ProductScreen.proof.test.ts', kit).startsWith('// @construct-generated');
 */
export function detailProofText(ctx, request, relPath, kit) {
  const { names, fields, rows } = ctx;
  const { lit } = kit;
  const Name = names.Name;
  const local = ctx.source === 'local';
  const command = `construct create proof ${Name} --feature ${request.feature} --shape detail --entity ${names.Entity} --fields ${ctx.request.fields}${sourceFlag(ctx)}${statesFlag(ctx)}`;
  const pv = proofViews(ctx);
  // #622: a state with no view (`skip-empty`, `skip-all`) is proven to show nothing, so a skip is a checked choice, never an unproven gap.
  const wants = (kind, shown) => (pv[kind] === 'shown' ? shown : 'nothing');
  const [item] = rows;
  const lineOf = (f) => `[${lit(`<dt>${labelOf(f.name)}</dt>`)}, ${lit(`<dd>${shownValue(f, item[f.name])}</dd>`)}]`;
  const localServiceTests = [
    `test(${lit(`${Name} service: the local store answers a seeded id with its item, with no network`)}, async () => {`,
    "  await withFetch(async () => { throw new Error('the local store must not use the network'); }, async () => {",
    `    const [first] = ${ctx.store.seed}({});`,
    '    const result = await ask(String(first.id));',
    "    expectState('The service given a seeded id', 'ready', resultState(result));",
    "    assert.deepEqual(result.status === 'ready' ? result.item : null, first, 'the item is the seeded row');",
    '  });',
    '});',
    '',
    `test(${lit(`${Name} service: an id the local store does not hold is not found`)}, async () => {`,
    "  expectState('The service given an unknown id', 'not-found', resultState(await ask('no-such-id')));",
    '});',
    '',
    `test(${lit(`${Name} service: a cancelled request is an error result`)}, async () => {`,
    '  const controller = new AbortController();',
    '  controller.abort();',
    `  expectState('The service given a cancelled request', 'error', resultState(await ${names.fetch}({ id: String(ITEM.id), signal: controller.signal })));`,
    '});',
  ];
  const L = [
    ...kit.header(`shape detail, kind render`, command),
    `// run: construct test proof ${kit.comment(request.feature)}   (on its own: npx tsx --test ${kit.comment(relPath)})`,
    '//',
    `// Proves the ${ctx.singular} details screen with no browser and no server: its four states from sample props (loading, not found, ready`,
    '// with every field label and value, error with role="alert"), that the controller renders the loading state first, the domain lines,',
    ...(local
      ? ['// and that the service answers a seeded id from its local store with no network, an unknown id as not found, and a cancelled request with an error result.']
      : ['// and that the service answers a 404, a 500, a wrong shape and a network failure with a typed result (fetch is stubbed).']),
    '// A failure names the state.',
    '',
    "import { test } from 'node:test';",
    "import assert from 'node:assert/strict';",
    "import { createElement } from 'react';",
    "import { renderToString } from 'react-dom/server';",
    `import { ${names.controller} } from '../../controllers/${names.controller}.controller';`,
    ...(local ? [`import { ${ctx.store.seed} } from '../../domain/${ctx.store.file}.domain';`] : []),
    `import { ${names.describe} } from '../../domain/${Name}.domain';`,
    `import { ${names.page} } from '../../pages/${names.page}.page';`,
    `import { ${names.fetch} } from '../../services/${Name}.service';`,
    `import type { ${names.Entity}, ${names.result}, ${names.state} } from '../../types';`,
    '',
    `const ITEM: ${names.Entity} = ${kit.rowLiteral(item)};`,
    `const LOADING_TEXT = ${lit(ctx.loadingText)};`,
    `const NOT_FOUND_TEXT = ${lit(ctx.notFoundText)};`,
    `const ERROR_TEXT = ${lit(ctx.errorText)};`,
    '',
    '/** What a person would see: the state of the screen, read off its markup. */',
    'function stateOf(html: string): string {',
    "  if (html.startsWith('<crashed')) return 'crashed';",
    "  if (html.includes('role=\"alert\"')) return 'error';",
    "  if (html.includes('role=\"status\"') && html.includes(LOADING_TEXT)) return 'loading';",
    "  if (html.includes('role=\"status\"') && html.includes(NOT_FOUND_TEXT)) return 'not-found';",
    "  if (html.includes('<dl')) return 'ready';",
    "  return 'nothing';",
    '}',
    '',
    '/** What the service answered, in the same words. */',
    `function resultState(result: ${names.result}): string {`,
    '  return result.status;',
    '}',
    '',
    ...kit.expectLines,
    '',
    `const render = (state: ${names.state}): string => {`,
    '  try {',
    `    return renderToString(createElement(${names.page}, { state }));`,
    '  } catch (error) {',
    "    return '<crashed: ' + (error instanceof Error ? error.message : String(error)) + '>';",
    '  }',
    '};',
    '',
    ...kit.fetchLines,
    `const ask = (id: string = String(ITEM.id)) => ${names.fetch}({ id, signal: new AbortController().signal });`,
    '',
    `test(${lit(`${Name} screen: the loading state${pv.loading === 'shown' ? '' : ' shows nothing (skipped)'}`)}, () => {`,
    `  expectState('The page given status loading', '${wants('loading', 'loading')}', stateOf(render({ status: 'loading' })));`,
    '});',
    '',
    `test(${lit(`${Name} screen: the not-found state${pv.empty === 'shown' ? '' : ' shows nothing (skipped)'}`)}, () => {`,
    `  expectState('The page given status not-found', '${wants('empty', 'not-found')}', stateOf(render({ status: 'not-found' })));`,
    '});',
    '',
    `test(${lit(`${Name} screen: the ready state, with every field label and value`)}, () => {`,
    `  const html = render({ status: 'ready', item: ITEM, rows: ${names.describe}({ item: ITEM }) });`,
    "  expectState('The page given the item', 'ready', stateOf(html));",
    '  const shown: string[][] = [',
    ...fields.map((f) => `    ${lineOf(f)},`),
    '  ];',
    "  shown.forEach((parts) => parts.forEach((part) => expectShown('The item', html, part)));",
    '});',
    '',
    `test(${lit(`${Name} screen: the error state${pv.error === 'shown' ? ', with role alert' : ' shows nothing (skipped)'}`)}, () => {`,
    "  const html = render({ status: 'error', message: ERROR_TEXT });",
    `  expectState('The page given an error', '${wants('error', 'error')}', stateOf(html));`,
    pv.error === 'shown' ? "  expectShown('The error', html, ERROR_TEXT);" : "  assert.equal(html.includes(ERROR_TEXT), false, 'a skipped error state does not show the message');",
    '});',
    '',
    `test(${lit(`${Name} controller: renders the loading state first`)}, () => {`,
    `  const html = renderToString(createElement(${names.controller}, { id: String(ITEM.id) }));`,
    `  expectState('The controller on its first render', '${wants('loading', 'loading')}', stateOf(html));`,
    "  assert.equal(html, render({ status: 'loading' }), 'the controller hands the hook state to the page and adds nothing');",
    `  assert.equal(renderToString(createElement(${names.controller}, {})), html, 'with no id prop it reads the address after the first render, so the first render is the same');`,
    '});',
    '',
    `test(${lit(`${Name} domain: one line per field, in order`)}, () => {`,
    `  const lines = ${names.describe}({ item: ITEM });`,
    `  assert.deepEqual(lines.map((line) => line.field), [${fields.map((f) => lit(f.name)).join(', ')}]);`,
    `  assert.deepEqual(lines.map((line) => line.label), [${fields.map((f) => lit(labelOf(f.name))).join(', ')}]);`,
    `  assert.deepEqual(lines.map((line) => line.value), [${fields.map((f) => lit(shownValue(f, item[f.name]))).join(', ')}]);`,
    '});',
    '',
    ...(local ? localServiceTests : [
    `test(${lit(`${Name} service: a good answer is the item`)}, async () => {`,
    '  await withFetch(respond(200, ITEM), async () => {',
    "    expectState('The service given an item', 'ready', resultState(await ask()));",
    '  });',
    '});',
    '',
    `test(${lit(`${Name} service: a 404 is not found`)}, async () => {`,
    '  await withFetch(respond(404, {}), async () => {',
    "    expectState('The service given a 404', 'not-found', resultState(await ask()));",
    '  });',
    '});',
    '',
    `test(${lit(`${Name} service: a 500 is an error result`)}, async () => {`,
    '  await withFetch(respond(500, {}), async () => {',
    "    expectState('The service given a 500', 'error', resultState(await ask()));",
    '  });',
    '});',
    '',
    `test(${lit(`${Name} service: a wrong shape is an error result`)}, async () => {`,
    "  await withFetch(respond(200, [ITEM]), async () => {",
    "    expectState('The service given a list instead of an item', 'error', resultState(await ask()));",
    '  });',
    `  const wrong = { ...ITEM, ${ctx.title.name}: ${ctx.title.type === 'string' ? '12345' : "'wrong'"} };`,
    '  await withFetch(respond(200, wrong), async () => {',
    "    expectState('The service given an item of the wrong shape', 'error', resultState(await ask()));",
    '  });',
    '});',
    '',
    `test(${lit(`${Name} service: a network failure is an error result`)}, async () => {`,
    "  await withFetch(async () => { throw new Error('offline'); }, async () => {",
    "    expectState('The service given a network failure', 'error', resultState(await ask()));",
    '  });',
    '});',
    '',
    `test(${lit(`${Name} service: asks for the item by its id, and the caller's AbortSignal reaches fetch`)}, async () => {`,
    '  const controller = new AbortController();',
    '  let seen: { url?: unknown; signal?: unknown } = {};',
    '  const original = globalThis.fetch;',
    '  globalThis.fetch = (async (url: unknown, init?: { signal?: unknown }) => { seen = { url, signal: init?.signal }; return respond(200, ITEM)(); }) as unknown as typeof fetch;',
    '  try {',
    `    await ${names.fetch}({ id: 'a b/c', signal: controller.signal });`,
    '  } finally {',
    '    globalThis.fetch = original;',
    '  }',
    `  assert.equal(seen.url, ${lit(`${ctx.endpoint}/a%20b%2Fc`)}, 'the id is part of the address, encoded');`,
    "  assert.equal(seen.signal, controller.signal, 'the service forwards the AbortSignal, so leaving the screen cancels the request');",
    '});',
    ]),
  ];
  return `${L.join('\n')}\n`;
}

/**
 * What a person types into a field of a sample form: text for a string, `12.5` for a number, a tick for a boolean.
 *
 * @param {{ name: string, type: string }} f The parsed field.
 * @returns {string|boolean} The typed value.
 *
 * @example
 * sampleValue({ name: 'price', type: 'number' }); // => '12.5'
 */
export const sampleValue = (f) => (f.type === 'boolean' ? true : f.type === 'number' ? '12.5' : `${f.name} 1`);
/**
 * The typed value of a field once the check has passed: numbers are numbers.
 *
 * @param {{ name: string, type: string }} f The parsed field.
 * @returns {string|number|boolean} The value the service is given.
 *
 * @example
 * typedValue({ name: 'price', type: 'number' }); // => 12.5
 */
export const typedValue = (f) => (f.type === 'boolean' ? true : f.type === 'number' ? 12.5 : `${f.name} 1`);
const badValue = (f) => (f.type === 'number' ? 'abc' : f.type === 'string' ? '' : false);

/**
 * The text of the render proof of a form screen: every field with its label and a typed input, the pure check (typed values for valid input,
 * a message per invalid field), the screen with those messages beside the fields, the submitting, submitted and error states, the
 * controller's first state, and the service with a stubbed fetch (the typed values are POSTed as JSON, a 500 and a network failure are
 * error results, the AbortSignal is forwarded).
 *
 * @param {object} ctx The proof context (shape context plus `errorText`, `submittedText`, `savingText`).
 * @param {{ feature: string }} request The proof request.
 * @param {string} relPath The project-relative path of the proof file, for its run line.
 * @param {ProofKit} kit The shared header and helpers.
 * @returns {string} The file text, ending with a newline.
 *
 * @example
 * formProofText(ctx, { feature: 'add-product' }, 'features/add-product/tests/generated/AddProductScreen.proof.test.ts', kit).includes('typed values');
 */
export function formProofText(ctx, request, relPath, kit) {
  const { names } = ctx;
  const { lit } = kit;
  const Name = names.Name;
  const inputs = inputFieldsOf(ctx.fields);
  const checked = inputs.filter((f) => f.type !== 'boolean');
  const prefix = kebab(Name);
  const local = ctx.source === 'local';
  const command = `construct create proof ${Name} --feature ${request.feature} --shape form --entity ${names.Entity} --fields ${ctx.request.fields}${sourceFlag(ctx)}`;
  const objectOf = (pick) => `{ ${inputs.map((f) => `${f.name}: ${typeof pick(f) === 'string' ? lit(pick(f)) : pick(f)}`).join(', ')} }`;
  const messageOf = (f) => (f.type === 'number' ? `${labelOf(f.name)} must be a number.` : `${labelOf(f.name)} is required.`);
  const numberField = inputs.find((f) => f.type === 'number');
  const firstText = inputs.find((f) => f.type === 'string');
  const localServiceTests = [
    `test(${lit(`${Name} service: a submit is saved into the local store, with no network`)}, async () => {`,
    `  const checked = ${names.validate}(VALID);`,
    "  assert.ok(checked.ok, 'the sample values are valid');",
    "  await withFetch(async () => { throw new Error('the local store must not use the network'); }, async () => {",
    "    expectState('The service given the checked values', 'submitted', (await send(checked.ok ? checked.input : TYPED)).status);",
    '  });',
    '});',
    '',
    `test(${lit(`${Name} store: saving adds one row with a fresh id and leaves the rows it is given alone`)}, () => {`,
    `  const rows = ${ctx.store.seed}({});`,
    '  const before = JSON.stringify(rows);',
    `  const saved = ${ctx.store.op}({ rows, input: TYPED });`,
    "  expectState('The store given one more row', String(rows.length + 1), String(saved.length));",
    "  assert.equal(JSON.stringify(rows), before, 'the rows it was given are unchanged');",
    "  assert.equal(new Set(saved.map((row) => String(row.id))).size, saved.length, 'every row has its own id');",
    "  assert.deepEqual(Object.fromEntries(Object.entries(saved[saved.length - 1]).filter(([key]) => key !== 'id')), TYPED, 'the new row holds the typed values');",
    '});',
    '',
    `test(${lit(`${Name} service: a cancelled request is an error result`)}, async () => {`,
    '  const controller = new AbortController();',
    '  controller.abort();',
    `  expectState('The service given a cancelled request', 'error', (await ${names.submit}({ input: TYPED, signal: controller.signal })).status);`,
    '});',
  ];
  const L = [
    ...kit.header(`shape form, kind render`, command),
    `// run: construct test proof ${kit.comment(request.feature)}   (on its own: npx tsx --test ${kit.comment(relPath)})`,
    '//',
    `// Proves the ${ctx.singular} form screen with no browser and no server: every field with its label and a typed input, the check (typed`,
    '// values for valid input, a message per invalid field, shown beside the field), the submitting, submitted and error states, that the',
    ...(local
      ? ['// controller renders the editing state first, and that the service saves the typed values into its local store with no network. A failure names the state.']
      : ['// controller renders the editing state first, and that the service POSTs the typed values (fetch is stubbed). A failure names the state.']),
    '',
    "import { test } from 'node:test';",
    "import assert from 'node:assert/strict';",
    "import { createElement } from 'react';",
    "import { renderToString } from 'react-dom/server';",
    `import { ${names.controller} } from '../../controllers/${names.controller}.controller';`,
    ...(local ? [`import { ${ctx.store.op}, ${ctx.store.seed} } from '../../domain/${ctx.store.file}.domain';`] : []),
    `import { ${names.validate} } from '../../domain/${Name}.domain';`,
    `import { ${names.page} } from '../../pages/${names.page}.page';`,
    `import { ${names.submit} } from '../../services/${Name}.service';`,
    `import type { ${names.input}, ${names.state}, ${names.values} } from '../../types';`,
    '',
    `const EMPTY: ${names.values} = ${objectOf((f) => (f.type === 'boolean' ? false : ''))};`,
    `const VALID: ${names.values} = ${objectOf((f) => sampleValue(f))};`,
    `const TYPED: ${names.input} = ${objectOf((f) => typedValue(f))};`,
    `const INVALID: ${names.values} = ${objectOf((f) => badValue(f))};`,
    `const ENDPOINT = ${lit(ctx.endpoint)};`,
    `const SUBMITTED_TEXT = ${lit(ctx.submittedText)};`,
    `const SAVING_TEXT = ${lit(ctx.savingText)};`,
    `const ERROR_TEXT = ${lit(ctx.errorText)};`,
    '',
    '/** What a person would see: the state of the screen, read off its markup. */',
    'function stateOf(html: string): string {',
    "  if (html.startsWith('<crashed')) return 'crashed';",
    "  if (html.includes('role=\"alert\"')) return 'error';",
    "  if (html.includes('role=\"status\"') && html.includes(SAVING_TEXT)) return 'submitting';",
    "  if (html.includes('role=\"status\"') && html.includes(SUBMITTED_TEXT)) return 'submitted';",
    "  if (html.includes('aria-invalid=\"true\"')) return 'invalid';",
    "  if (html.includes('<form')) return 'editing';",
    "  return 'nothing';",
    '}',
    '',
    ...kit.expectLines,
    '',
    `const noop = (): void => {};`,
    `const render = (state: ${names.state}): string => {`,
    '  try {',
    `    return renderToString(createElement(${names.page}, { state, onChange: noop, onSubmit: noop, onReset: noop }));`,
    '  } catch (error) {',
    "    return '<crashed: ' + (error instanceof Error ? error.message : String(error)) + '>';",
    '  }',
    '};',
    '',
    ...kit.fetchLines,
    `const send = (input: ${names.input}) => ${names.submit}({ input, signal: new AbortController().signal });`,
    '',
    `test(${lit(`${Name} screen: every field with its label and a typed input`)}, () => {`,
    `  const html = render({ status: 'editing', values: EMPTY, errors: {} });`,
    "  expectState('The form given empty values', 'editing', stateOf(html));",
    '  const fields: [string, string, string][] = [',
    ...inputs.map((f) => `    [${lit(`${prefix}-${kebab(f.name)}`)}, ${lit(labelOf(f.name))}, ${lit(f.type === 'number' ? 'number' : f.type === 'boolean' ? 'checkbox' : 'text')}],`),
    '  ];',
    '  fields.forEach(([id, label, type]) => {',
    "    expectShown('The field ' + id, html, '<label for=\"' + id + '\">' + label + '</label>');",
    "    const tag = new RegExp('<input[^>]*\\\\bid=\"' + id + '\"[^>]*>').exec(html)?.[0] ?? '';",
    "    expectShown('The input of ' + id, tag, 'type=\"' + type + '\"');",
    '  });',
    '});',
    '',
    `test(${lit(`${Name} domain: valid values give the typed values`)}, () => {`,
    `  const result = ${names.validate}(VALID);`,
    "  expectState('The check given valid values', 'valid', result.ok ? 'valid' : 'invalid');",
    "  assert.deepEqual(result.ok ? result.input : null, TYPED, 'the typed values: numbers are numbers, text is trimmed');",
    '});',
    '',
    ...(checked.length ? [
      `test(${lit(`${Name} domain: invalid values give a message per field`)}, () => {`,
      `  const result = ${names.validate}(INVALID);`,
      "  expectState('The check given invalid values', 'invalid', result.ok ? 'valid' : 'invalid');",
      `  const errors: Record<string, string | undefined> = result.ok ? {} : { ...result.errors };`,
      ...checked.map((f) => `  expectState('The check of the ${f.name} field', 'invalid', errors.${f.name} === undefined ? 'valid' : 'invalid');`),
      `  assert.deepEqual(errors, { ${checked.map((f) => `${f.name}: ${lit(messageOf(f))}`).join(', ')} });`,
      '});',
      '',
      ...(numberField ? [
        `test(${lit(`${Name} domain: a blank number is required, not zero`)}, () => {`,
        `  const result = ${names.validate}({ ...VALID, ${numberField.name}: '  ' });`,
        "  expectState('The check given a blank number', 'invalid', result.ok ? 'valid' : 'invalid');",
        `  assert.equal(result.ok ? '' : result.errors.${numberField.name}, ${lit(`${labelOf(numberField.name)} is required.`)});`,
        '});',
        '',
      ] : []),
      `test(${lit(`${Name} screen: a message beside each invalid field`)}, () => {`,
      `  const result = ${names.validate}(INVALID);`,
      "  const html = render({ status: 'editing', values: INVALID, errors: result.ok ? {} : result.errors });",
      "  expectState('The form given the messages of a failed check', 'invalid', stateOf(html));",
      ...checked.flatMap((f) => [`  expectShown('The message of ${f.name}', html, ${lit(`>${messageOf(f)}</span>`)});`, `  expectShown('The field ${f.name}', html, ${lit(`id="${prefix}-${kebab(f.name)}-error"`)});`]),
      '});',
      '',
    ] : []),
    `test(${lit(`${Name} screen: the submitting state disables the form`)}, () => {`,
    "  const html = render({ status: 'submitting', values: VALID });",
    "  expectState('The form given status submitting', 'submitting', stateOf(html));",
    "  expectShown('The submitting form', html, 'disabled');",
    '});',
    '',
    `test(${lit(`${Name} screen: the submitted state`)}, () => {`,
    "  const html = render({ status: 'submitted' });",
    "  expectState('The form given status submitted', 'submitted', stateOf(html));",
    "  expectShown('The submitted screen', html, 'Add another');",
    '});',
    '',
    `test(${lit(`${Name} screen: the error state, with role alert, keeps what was typed`)}, () => {`,
    "  const html = render({ status: 'error', values: VALID, message: ERROR_TEXT });",
    "  expectState('The form given an error', 'error', stateOf(html));",
    "  expectShown('The error', html, ERROR_TEXT);",
    ...(firstText ? [`  expectShown('The form after an error', html, ${lit(`value="${sampleValue(firstText)}"`)});`] : []),
    '});',
    '',
    `test(${lit(`${Name} controller: renders the editing state first`)}, () => {`,
    `  const html = renderToString(createElement(${names.controller}, {}));`,
    "  expectState('The controller on its first render', 'editing', stateOf(html));",
    "  assert.equal(html, render({ status: 'editing', values: EMPTY, errors: {} }), 'the controller hands the hook state to the page and adds nothing');",
    '});',
    '',
    ...(local ? localServiceTests : [
    `test(${lit(`${Name} service: the stubbed submit is called with the typed values`)}, async () => {`,
    `  const checked = ${names.validate}(VALID);`,
    "  assert.ok(checked.ok, 'the sample values are valid');",
    '  let call: { url?: unknown; method?: unknown; type?: unknown; body?: unknown } = {};',
    '  const original = globalThis.fetch;',
    "  globalThis.fetch = (async (url: unknown, init?: { method?: string; headers?: Record<string, string>; body?: string }) => { call = { url, method: init?.method, type: init?.headers?.['Content-Type'], body: init?.body }; return respond(201, {})(); }) as unknown as typeof fetch;",
    '  try {',
    "    expectState('The service given the checked values', 'submitted', (await send(checked.ok ? checked.input : TYPED)).status);",
    '  } finally {',
    '    globalThis.fetch = original;',
    '  }',
    "  assert.equal(call.url, ENDPOINT, 'it posts to the endpoint');",
    "  assert.equal(call.method, 'POST');",
    "  assert.equal(call.type, 'application/json');",
    "  assert.deepEqual(JSON.parse(String(call.body)), TYPED, 'the body is the typed values (numbers are numbers)');",
    '});',
    '',
    `test(${lit(`${Name} service: a 500 is an error result`)}, async () => {`,
    '  await withFetch(respond(500, {}), async () => {',
    "    expectState('The service given a 500', 'error', (await send(TYPED)).status);",
    '  });',
    '});',
    '',
    `test(${lit(`${Name} service: a network failure is an error result`)}, async () => {`,
    "  await withFetch(async () => { throw new Error('offline'); }, async () => {",
    "    expectState('The service given a network failure', 'error', (await send(TYPED)).status);",
    '  });',
    '});',
    '',
    `test(${lit(`${Name} service: the caller's AbortSignal reaches fetch`)}, async () => {`,
    '  const controller = new AbortController();',
    '  let seen: unknown;',
    '  const original = globalThis.fetch;',
    '  globalThis.fetch = (async (_url: unknown, init?: { signal?: unknown }) => { seen = init?.signal; return respond(201, {})(); }) as unknown as typeof fetch;',
    '  try {',
    `    await ${names.submit}({ input: TYPED, signal: controller.signal });`,
    '  } finally {',
    '    globalThis.fetch = original;',
    '  }',
    "  assert.equal(seen, controller.signal, 'the service forwards the AbortSignal, so leaving the screen cancels the request');",
    '});',
    ]),
  ];
  return `${L.join('\n')}\n`;
}
