// Route layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Navigation entry point. Delegates to the controller.
import PortfolioRedesignedController from "../controller/PortfolioRedesignedController.jsx";

export const path = "/portfolio";

export default function PortfolioRedesignedRoute() {
  return <PortfolioRedesignedController />;
}
