// Page layer — generated by line-matcher from the design. Props in, JSX out; no business logic.
import OrderRow from "../component/OrderRow.jsx";

export default function OrdersPage({
  status,
  error,
  orderCount,
  totalValue,
  rows,
  selectedId,
  formValues,
  onEdit,
  onDelete,
  onCancel,
}) {
  return (
    <main className="page">
      {status === "loading" && <p className="status">Loading…</p>}
      {error && (
        <p role="alert" className="error">
          {error}
        </p>
      )}
      <header className="header">
        <h1>Orders</h1>
        <p className="meta">
          <span>{orderCount}</span>
          {" orders · total value "}
          <span>{totalValue}</span>
        </p>
      </header>

      <form className="card form">
        <input name="customer" placeholder="Customer" required />
        <input name="total" type="number" placeholder="Total" required />
        <input name="notes" placeholder="Notes" required />
        <button type="submit" className="primary">
          Save
        </button>
        <button type="button" onClick={onCancel}>
          Cancel
        </button>
      </form>

      <table className="card table">
        <thead>
          <tr>
            <th>Order</th>
            <th>Customer</th>
            <th>Total</th>
            <th>Placed</th>
            <th>Status</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <OrderRow
              key={row.id}
              row={row}
              selected={row.id === selectedId}
              onEdit={onEdit}
              onDelete={onDelete}
            />
          ))}
        </tbody>
      </table>
    </main>
  );
}
