// Controller layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Connects the workflow and domain to the page. No business logic here.
import { useMachine } from "@xstate/react";
import { portfolioFigma1Workflow } from "../workflow/portfolio-figma-1.workflow.js";
import * as domain from "../domain/portfolio-figma-1.domain.js";
import PortfolioFigma1Page from "../page/PortfolioFigma1Page.jsx";

// PLACEHOLDER: "row.savingsPct" is provided by the controller for each row. The design showed "14.6%", "11.3%", "9.3%", "10.6%", "9.4%", "3.5%".
function getSavingsPct(row) {
  return "14.6%";
}

// PLACEHOLDER: "suggest" page action — decide what it should do.
function handleSuggest() {
  console.warn("handleSuggest is a placeholder");
}

// PLACEHOLDER: "suggest" page action — decide what it should do.
function handleSuggest2() {
  console.warn("handleSuggest2 is a placeholder");
}

export default function PortfolioFigma1Controller() {
  const [state, send] = useMachine(portfolioFigma1Workflow);
  const { data, items, selectedId, error } = state.context;

  return (
    <PortfolioFigma1Page
      status={String(state.value)}
      error={error}
      categoryCount={domain.categoryCount(items)}
      spendYouManage={domain.spendYouManage(data)}
      refreshedAt={domain.refreshedAt(data)}
      headline={domain.headline(data)}
      improving={domain.improving(items)}
      declining={domain.declining(items)}
      spendCard={domain.spendCard(items)}
      spendYoy={domain.spendYoy(items)}
      largestName={domain.largestName(data)}
      largestShare={domain.largestShare(data)}
      savingsCard={domain.savingsCard(data)}
      acceptedPct={domain.acceptedPct(data)}
      acceptedCount={domain.acceptedCount(items)}
      resilienceTotal={domain.resilienceTotal(data)}
      impactHigh={domain.impactHigh(data)}
      impactMedium={domain.impactMedium(data)}
      impactLow={domain.impactLow(data)}
      highCategories={domain.highCategories(items)}
      savingsCount={domain.savingsCount(data)}
      savingsTarget={domain.savingsTarget(items)}
      oldestDays={domain.oldestDays(items)}
      riskCount={domain.riskCount(items)}
      riskCategories={domain.riskCategories(items)}
      riskTarget={domain.riskTarget(items)}
      rows={domain
        .toPortfolioFigma1Rows(items)
        .map((row) => ({ ...row, savingsPct: getSavingsPct(row) }))}
      selectedId={selectedId}
      onOpen={(id) => send({ type: "OPEN", id })}
      onSuggest={handleSuggest}
      onSuggest={handleSuggest2}
    />
  );
}
