// Route layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Navigation entry point. Delegates to the controller.
import ContactsController from "../controller/ContactsController.jsx";

export const path = "/contacts";

export default function ContactsRoute() {
  return <ContactsController />;
}
