// Page layer — generated by line-matcher from the design. Props in, JSX out; no business logic.
import ContactRow from "../component/ContactRow.jsx";

export default function ContactsPage({
  status,
  error,
  contactCount,
  directoryUpdated,
  rows,
  selectedId,
  formValues,
  onEdit,
  onDelete,
  onSave,
  onCancel,
}) {
  return (
    <main className="page">
      {status === "loading" && <p className="status">Loading…</p>}
      {error && (
        <p role="alert" className="error">
          {error}
        </p>
      )}
      <header className="header">
        <h1>Contacts</h1>
        <p className="meta">
          <span>{contactCount}</span>
          {" contacts · directory updated "}
          <span>{directoryUpdated}</span>
        </p>
      </header>

      <form
        className="card form"
        key={selectedId ?? "new"}
        onSubmit={(e) => {
          e.preventDefault();
          onSave(Object.fromEntries(new FormData(e.currentTarget)));
        }}
      >
        <input
          name="first"
          placeholder="First name"
          required
          defaultValue={formValues.first ?? ""}
        />
        <input name="last" placeholder="Last name" required defaultValue={formValues.last ?? ""} />
        <input name="email" placeholder="Email" required defaultValue={formValues.email ?? ""} />
        <input name="city" placeholder="City" required defaultValue={formValues.city ?? ""} />
        <button type="submit" className="primary">
          Save
        </button>
        <button type="button" onClick={onCancel}>
          Cancel
        </button>
      </form>

      <table className="card table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Initials</th>
            <th>Email</th>
            <th>City</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <ContactRow
              key={row.id}
              row={row}
              selected={row.id === selectedId}
              onEdit={onEdit}
              onDelete={onDelete}
            />
          ))}
        </tbody>
      </table>
    </main>
  );
}
