// Domain layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Pure functions only: no network, storage or DOM.

export function asText(v) {
  return String(v);
}

export function moneyCompact(v) {
  const n = Number(v);
  const units = [
    [1e9, "B"],
    [1e6, "M"],
    [1e3, "K"],
  ];
  for (const [size, suffix] of units) {
    if (Math.abs(n) >= size) return "$" + (n / size).toFixed(1) + suffix;
  }
  return "$" + n.toFixed(0);
}

export function percent(v) {
  return (Number(v) * 100).toFixed(1) + "%";
}

// Rows for the "metrics" list.
export function toMetricRows(items) {
  return items.map((item) => ({
    id: item.id,
  }));
}

// "regionCount" = count. Design showed "4".
export function regionCount(items) {
  return asText(items.length);
}

// "totalRevenue" = sum(revenue), shown as moneyCompact. Design showed "$364.0M".
export function totalRevenue(items) {
  return moneyCompact(items.reduce((s, x) => s + Number(x.revenue), 0));
}

// "bestRevenue" = max(revenue), shown as moneyCompact. Design showed "$120.0M".
export function bestRevenue(items) {
  return moneyCompact(items.length ? Math.max(...items.map((x) => Number(x.revenue))) : 0);
}

// "lowestCost" = min(cost), shown as moneyCompact. Design showed "$33.0M".
export function lowestCost(items) {
  return moneyCompact(items.length ? Math.min(...items.map((x) => Number(x.cost))) : 0);
}

// "avgConversion" = average(conversion), shown as percent. Design showed "18.5%".
export function avgConversion(items) {
  return percent(
    items.length ? items.reduce((s, x) => s + Number(x.conversion), 0) / items.length : 0,
  );
}

// TODO: "asOf" (design showed "26 Sep 2026") was skipped in Q&A — decide where it comes from.
export function asOf() {
  return "—";
}

export function findMetric(items, id) {
  return items.find((item) => item.id === id) ?? null;
}
