// Controller layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Connects the workflow and domain to the page. No business logic here.
import { useMachine } from "@xstate/react";
import { productsWorkflow } from "../workflow/products.workflow.js";
import * as domain from "../domain/products.domain.js";
import ProductsPage from "../page/ProductsPage.jsx";

export default function ProductsController() {
  const [state, send] = useMachine(productsWorkflow);
  const { items, selectedId, error } = state.context;

  return (
    <ProductsPage
      status={String(state.value)}
      error={error}
      productCount={domain.productCount(items)}
      stockTotal={domain.stockTotal(items)}
      avgPrice={domain.avgPrice(items)}
      rows={domain.toProductRows(items)}
      selectedId={selectedId}
      formValues={domain.toFormValues(domain.findProduct(items, selectedId))}
      onEdit={(id) => send({ type: "EDIT", id })}
      onDelete={(id) => send({ type: "DELETE", id })}
      onSave={(values) => send({ type: "SAVE", data: domain.toProductInput(values) })}
      onCancel={() => send({ type: "CANCEL" })}
    />
  );
}
