// Controller layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Connects the workflow and domain to the page. No business logic here.
import { useMachine } from "@xstate/react";
import { rosterWorkflow } from "../workflow/roster.workflow.js";
import * as domain from "../domain/roster.domain.js";
import RosterPage from "../page/RosterPage.jsx";

export default function RosterController() {
  const [state, send] = useMachine(rosterWorkflow);
  const { items, selectedId, error } = state.context;

  return (
    <RosterPage
      status={String(state.value)}
      error={error}
      projectCount={domain.projectCount(items)}
      plannedTotal={domain.plannedTotal(items)}
      forecastTotal={domain.forecastTotal(items)}
      rows={domain.toRosterRows(items)}
      selectedId={selectedId}
      formValues={domain.toFormValues(domain.findRoster(items, selectedId))}
      onEdit={(id) => send({ type: "EDIT", id })}
      onDelete={(id) => send({ type: "DELETE", id })}
      onSave={(values) => send({ type: "SAVE", data: domain.toRosterInput(values) })}
      onCancel={() => send({ type: "CANCEL" })}
    />
  );
}
