// Page layer — generated by line-matcher from the design. Props in, JSX out; no business logic.
import PortfolioRedesignedRow from "../component/PortfolioRedesignedRow.jsx";

export default function PortfolioRedesignedPage({
  status,
  error,
  refreshedAt,
  headline,
  improving,
  declining,
  baselineSpend,
  highCategories,
  savingsRange,
  qualifiedCount,
  coveredCount,
  resilienceTotal,
  savingsCount,
  oldestDays,
  qualifiedInitiatives,
  rows,
  selectedId,
  onOpen,
  onSuggest,
}) {
  return (
    <main className="page">
      {status === "loading" && <p className="status">Loading…</p>}
      {error && (
        <p role="alert" className="error">
          {error}
        </p>
      )}
      <header className="header">
        <h1>Portfolio health</h1>
        <p className="meta">
          {"Max · your portfolio summary · "}
          <span>{refreshedAt}</span>
        </p>
      </header>

      <section className="card">
        <h2>
          <span>{headline}</span>
        </h2>
        <p>
          {"Improving: "}
          <span>{improving}</span>
        </p>
        <p>
          {"Declining: "}
          <span>{declining}</span>
        </p>
        <button onClick={onSuggest}>Who could take 20% of this volume?</button>
        <button onClick={onSuggest}>What am I missing?</button>
      </section>

      <h2>Your portfolio at a glance</h2>
      <div className="cards">
        <div className="card metric">
          <p className="label">Baseline spend</p>
          <p className="big">
            <span>{baselineSpend}</span>
          </p>
          <p className="note">
            <span>{highCategories}</span>
            {" categories carry at least one high."}
          </p>
          <p className="note">{"Jan 2020 - Mar 2020 · As of 14 Mar, 09:00"}</p>
        </div>
        <div className="card metric">
          <p className="label">Potential savings</p>
          <p className="big">
            <span>{savingsRange}</span>
          </p>
          <p className="note">
            {"Identified across "}
            <span>{qualifiedCount}</span>
            {" qualified opportunities"}
          </p>
        </div>
        <div className="card metric">
          <p className="label">Categories covered</p>
          <p className="big">
            <span>{coveredCount}</span>
          </p>
          <p className="note">
            Risk reduction awaiting a decision. Not measured in savings, so it is counted
            separately.
          </p>
        </div>
        <div className="card metric">
          <p className="label">Resilience initiatives</p>
          <p className="big">
            <span>{resilienceTotal}</span>
          </p>
          <p className="note">High · Medium · Low</p>
        </div>
        <div className="card metric">
          <p className="label">Savings initiatives</p>
          <p className="big">
            <span>{savingsCount}</span>
          </p>
          <p className="note">
            {
              "Savings initiatives raised but not yet accepted by an owner. Oldest has been waiting "
            }
            <span>{oldestDays}</span>
            {" days."}
          </p>
        </div>
        <div className="card metric">
          <p className="label">Qualified initiatives</p>
          <p className="big">
            <span>{qualifiedInitiatives}</span>
          </p>
          <p className="note">Accepted · Pending</p>
        </div>
      </div>

      <h2>Category overview</h2>
      <p className="meta">
        Order based on top spend categories (Top 10) within that ordered by the ones needing max
        attention).
      </p>
      <table className="card table">
        <thead>
          <tr>
            <th>#</th>
            <th>Category</th>
            <th>Spend</th>
            <th>Maturity</th>
            <th>Potential savings</th>
            <th>Composite risk score</th>
            <th>Spend change</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {rows.map((row) => (
            <PortfolioRedesignedRow
              key={row.id}
              row={row}
              selected={row.id === selectedId}
              onOpen={onOpen}
            />
          ))}
        </tbody>
      </table>
    </main>
  );
}
