// Controller layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Connects the workflow and domain to the page. No business logic here.
import { useMachine } from "@xstate/react";
import { contactsWorkflow } from "../workflow/contacts.workflow.js";
import * as domain from "../domain/contacts.domain.js";
import ContactsPage from "../page/ContactsPage.jsx";

// PLACEHOLDER: "directoryUpdated" is provided by the controller. The design showed "26 Sep 2026".
function getDirectoryUpdated() {
  return "26 Sep 2026";
}

// PLACEHOLDER: "row.fullName" is provided by the controller for each row. The design showed "Lena Kumar", "Arjun Rao", "Mia Shah".
function getFullName(row) {
  return "Lena Kumar";
}

export default function ContactsController() {
  const [state, send] = useMachine(contactsWorkflow);
  const { items, selectedId, error } = state.context;

  return (
    <ContactsPage
      status={String(state.value)}
      error={error}
      contactCount={domain.contactCount(items)}
      directoryUpdated={getDirectoryUpdated()}
      rows={domain.toContactRows(items).map((row) => ({ ...row, fullName: getFullName(row) }))}
      selectedId={selectedId}
      formValues={domain.toFormValues(domain.findContact(items, selectedId))}
      onEdit={(id) => send({ type: "EDIT", id })}
      onDelete={(id) => send({ type: "DELETE", id })}
      onSave={(values) => send({ type: "SAVE", data: domain.toContactInput(values) })}
      onCancel={() => send({ type: "CANCEL" })}
    />
  );
}
