// Domain layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Pure functions only: no network, storage or DOM.

export function asText(v) {
  return String(v);
}

export function moneyFull(v) {
  return "$" + Number(v).toLocaleString("en-US");
}

export function dateShort(v) {
  const d = new Date(v);
  const m = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  return d.getUTCDate() + " " + m[d.getUTCMonth()] + " " + d.getUTCFullYear();
}

// Rows for the "products" list.
export function toProductRows(items) {
  return items.map((item) => ({
    id: item.id,
    name: asText(item.name),
    price: moneyFull(item.price),
    stock: asText(item.stock),
    addedOn: dateShort(item.addedOn),
  }));
}

// "productCount" = count. Design showed "3".
export function productCount(items) {
  return asText(items.length);
}

// "stockTotal" = sum(stock). Design showed "287".
export function stockTotal(items) {
  return asText(items.reduce((s, x) => s + Number(x.stock), 0));
}

// "avgPrice" = average(price), shown as moneyFull. Design showed "$4,050".
export function avgPrice(items) {
  return moneyFull(
    items.length ? items.reduce((s, x) => s + Number(x.price), 0) / items.length : 0,
  );
}

export function findProduct(items, id) {
  return items.find((item) => item.id === id) ?? null;
}

// Form text -> the types the API expects (taken from the example request body).
export function toProductInput(values) {
  return {
    name: String(values.name ?? "").trim(),
    price: Number(values.price),
    stock: Number(values.stock),
  };
}

// Raw values to prefill the form when an item is selected.
export function toFormValues(item) {
  if (!item) return {};
  return {
    name: item.name,
    price: item.price,
    stock: item.stock,
  };
}
