// @construct-generated tests v1 - LOCKED, do not edit (#348)
// Generated by `construct generate tests`. Regenerated whenever the workflow changes; edits are refused.
// To change it: clone it to features/login/tests/ (one level up), where nothing regenerates it.
// feature: "login"
// machine: "login" ("workflows/Login.tsx"), key "login"
// scenario: "happy-path" - "Happy path"
// route: idle → success
// machine-hash: sha256:56ae9c5ebfe692bf1f2b2f6bc5c96d3ab0dca54164c1d3f1ea04dea92485b019
// scenario-hash: sha256:3ab3c239235456583ae482502d187a81210c31cbbd48873f7761259df6632003

// Given the flow starts in *idle*
// When "submit" happens — only if it is valid
// Then the flow moves to *success*
// And the flow ends — *success* is an end state

import { test, expect, type Page } from '@playwright/test';

const START_URL: string | null = "/login";
const MACHINE = "login";

const harness = (selector: string, why: string) =>
  new Error(
    `Test harness problem, not a bug in the page: the test harness expected ${selector}. ` +
      `${why} Construct binds workflow events to elements by convention (data-testid = the event name in kebab-case; ` +
      `data-flow / data-flow-state on the element that shows the machine's state). ` +
      `Add the attribute (or scaffold the page with \`construct create page --from\`); do not file a product bug for this.`,
  );

async function required(page: Page, selector: string, why: string) {
  const el = page.locator(selector).first();
  try {
    await el.waitFor({ state: 'attached', timeout: 5_000 });
  } catch {
    throw harness(selector, why);
  }
  return el;
}

async function trigger(page: Page, testId: string, event: string) {
  const el = await required(page, `[data-testid="${testId}"]`, `It is what the workflow event ${event} binds to.`);
  await el.click();
}

async function expectFlowState(page: Page, machine: string, state: string, timeout = 5_000) {
  const el = await required(page, `[data-flow="${machine}"][data-flow-state]`, `It shows the state of the ${machine} workflow.`);
  await expect(el).toHaveAttribute('data-flow-state', state, { timeout });
}

test("login / login / Happy path", async ({ page }) => {
  test.fixme(true, "needs a fixture where the guard \"isValid\" holds");
  if (START_URL === null) return;
  await page.goto(START_URL);
  await expectFlowState(page, MACHINE, "idle");
  // When "submit" happens
  await trigger(page, "submit", "SUBMIT");
  await expectFlowState(page, MACHINE, "success");
});
