// Page layer — generated by line-matcher from the design. Props in, JSX out; no business logic.

export default function MetricsPage({
  status,
  error,
  regionCount,
  totalRevenue,
  bestRevenue,
  lowestCost,
  avgConversion,
  asOf,
}) {
  return (
    <main className="page">
      {status === "loading" && <p className="status">Loading…</p>}
      {error && (
        <p role="alert" className="error">
          {error}
        </p>
      )}
      <header className="header">
        <h1>Metrics</h1>
        <p className="meta">
          <span>{regionCount}</span>
          {" regions · revenue "}
          <span>{totalRevenue}</span>
          {" · best region "}
          <span>{bestRevenue}</span>
          {" · lowest cost "}
          <span>{lowestCost}</span>
          {" · conversion "}
          <span>{avgConversion}</span>
          {" · as of "}
          <span>{asOf}</span>
        </p>
      </header>
    </main>
  );
}
