// Route layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Navigation entry point. Delegates to the controller.
import ProductsController from "../controller/ProductsController.jsx";

export const path = "/products";

export default function ProductsRoute() {
  return <ProductsController />;
}
