import fs from 'node:fs'; import path from 'node:path'; import {loadConfig} from './config.mjs'; import {walk,rel} from './fs.mjs';
const ext=new Set(['.ts','.tsx','.js','.jsx']);
const imports=(s)=>[...s.matchAll(/(?:import\s+(?:type\s+)?[\s\S]*?from\s*|import\s*\()(['"])(.*?)\1/g)].map(m=>m[2]);
function layerOf(r){if(/^app\/.*page\.(tsx|ts|jsx|js)$/.test(r))return'route'; const m=r.match(/^features\/[^/]+\/(controllers|workflows|hooks|domain|services|pages|components)\//); if(!m)return null; return {controllers:'controller',workflows:'workflow',hooks:'hook',domain:'domain',services:'service',pages:'page',components:'component'}[m[1]]}
function exception(config,rule,file){const now=Date.now(); return config.exceptions.some(e=>(e.rule?[e.rule]:e.rules||[]).includes(rule)&&match(e.path,file)&&(!e.expires||new Date(e.expires).getTime()>=now));}
function match(glob,file){const g=glob.replaceAll('**','§').replaceAll('*','[^/]*').replaceAll('§','.*'); return new RegExp('^'+g+'$').test(file)}
function violation(config,out,rule,file,line,message,why,expected=[]){const severity=config.rules[rule]?.severity||'error'; if(severity==='off'||exception(config,rule,file))return; out.push({rule,severity,file,line,message,why,expected,suggestedFix:expected.length?`Move the responsibility to ${expected.join(' or ')}.`:undefined});}
export function validateProject(root){const config=loadConfig(root), files=walk(root).filter(p=>ext.has(path.extname(p))), out=[]; const featureRoot=config.features.root||'features';
 if(!fs.existsSync(path.join(root,featureRoot))) violation(config,out,'SLICE-001',`${featureRoot}/`,'1','Missing feature root.','Feature slices are mandatory.',['features/<feature>']);
 for(const p of files){const r=rel(root,p), l=layerOf(r), s=fs.readFileSync(p,'utf8'), lines=s.split('\n'); const importsList=imports(s); const lineOf=x=>{const i=s.slice(0,x).split('\n').length;return i};
  if(l==='route'){if(!importsList.some(x=>/controllers?\//.test(x))) violation(config,out,'ROUTE-001',r,1,'Route does not import a controller.','Routes are navigation entry points and must delegate.',['controller']); if(/\b(fetch|useMachine|useActor|localStorage|sessionStorage)\b/.test(s)) violation(config,out,'ROUTE-002',r,1,'Route contains application logic or effects.','Routes must remain thin.',['controller']);}
  if(l==='page'){for(const [rule,re] of [['PAGE-002',/workflows?\//],['PAGE-003',/services?\//],['PAGE-005',/domain\//]]){const m=s.match(re);if(m)violation(config,out,rule,r,lineOf(m.index),'Page imports a forbidden application layer.','Pages are presentation-only.',['component','types'])} for(const [rule,re,msg] of [['PAGE-004',/\bfetch\s*\(/,'Page calls fetch().'],['PAGE-006',/\b(useMachine|useActor|createMachine)\b/,'Page uses workflow/application state.']]){const m=s.match(re);if(m)violation(config,out,rule,r,lineOf(m.index),msg,'Pages cannot own application flow.',['controller','workflow'])}}
  if(l==='component'){const m=s.match(/(?:controllers?|workflows?|services?|domain)\//);if(m) violation(config,out,'COMPONENT-003',r,lineOf(m.index),'Component imports application logic.','Components are reusable presentation and local UI state only.',['props','component'])}
  if(l==='workflow'&&/from\s*['"]react['"]|from\s*['"][^'"]*react\//.test(s))violation(config,out,'WORKFLOW-001',r,1,'Workflow imports React/UI.','Workflow logic must be UI-independent.',['service','domain','types']);
  if(l==='service'&&/from\s*['"]react['"]|from\s*['"][^'"]*react\//.test(s))violation(config,out,'SERVICE-002',r,1,'Service imports React/UI.','Services own external effects, not rendering.',['api','domain','types']);
  if(l==='domain'){const m=s.match(/\b(fetch|window|document|localStorage|sessionStorage|navigator)\b/);if(m)violation(config,out,'DOMAIN-001',r,lineOf(m.index),'Domain code uses an external effect.','Domain is pure by default.',['pure function'])}
  const feature=r.match(/^features\/([^/]+)\//)?.[1]; if(feature){const foreign=importsList.find(x=>x.startsWith('@features/')||x.match(/^\.\.\/.*features\//)); if(foreign)violation(config,out,'SLICE-002',r,1,'Cross-feature import detected.','Features may only consume another feature through its public index API.',['features/<name>/index.ts'])}
  const exported=[...s.matchAll(/\bexport\s+(?:default\s+)?(?:async\s+)?(?:function|class|const|let|var)\s+([A-Za-z_$][\w$]*)/g)]; if(exported.length>3)violation(config,out,'MODULE-001',r,1,`File declares ${exported.length} primary exports.`,'Prefer one primary module per file.',['split into focused modules']);
 }
 return {config,violations:out,ok:!out.some(v=>v.severity==='error')}; }
