// Route layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Navigation entry point. Delegates to the controller.
import PortfolioFigma1Controller from "../controller/PortfolioFigma1Controller.jsx";

export const path = "/portfolio";

export default function PortfolioFigma1Route() {
  return <PortfolioFigma1Controller />;
}
