// Route layer — generated by line-matcher. Do not add logic that belongs to another layer.
// Navigation entry point. Delegates to the controller.
import RosterController from "../controller/RosterController.jsx";

export const path = "/roster";

export default function RosterRoute() {
  return <RosterController />;
}
