// Component layer — generated by line-matcher. Reusable presentation only.
export default function ContactRow({ row, selected, onEdit, onDelete }) {
  return (
    <tr data-selected={selected ? "true" : undefined}>
      <td>{row.fullName}</td>
      <td>LK</td>
      <td>{row.email}</td>
      <td>{row.city}</td>
      <td className="actions">
        <button onClick={() => onEdit(row.id)}>Edit</button>
        <button>Call</button>
        <button className="danger" onClick={() => onDelete(row.id)}>
          Delete
        </button>
      </td>
    </tr>
  );
}
